const assert=require('assert/strict'),{rhythmVariation,guidedVocalParts,relateParts}=require('../src/composer');
const ids=['drums','kick','bass','chords','pad','lead','harmony','screech','darkmelody','melody','pluck','arp'];let runs=0,notes=0;
const sig=e=>JSON.stringify(e.map(n=>[n.tick,n.dur]));const steps=[0,2,3,5,7,8,10];
for(const id of ids){const poly=['chords','pad','harmony'].includes(id),events=[];for(let bar=0;bar<4;bar++)for(const t of [0,480,960,1440])for(const midi of poly?[60,63,67]:[id==='drums'?38:60])events.push({tick:bar*1920+t,dur:300,midi,vel:95});const part={id,events,part:{}};const signatures=new Set();for(let i=0;i<100;i++){for(const strength of ['subtle','explore','wild']){const p=rhythmVariation(part,4,'test'+i,strength,steps,0);assert.deepEqual(p,rhythmVariation(part,4,'test'+i,strength,steps,0));assert.ok(p.events.length);p.events.forEach(e=>{assert.ok([e.tick,e.dur,e.midi,e.vel].every(Number.isInteger));assert.ok(e.tick>=0&&e.dur>0&&e.tick+e.dur<=7680&&e.midi>=0&&e.midi<128&&e.vel>0&&e.vel<128);});signatures.add(sig(p.events));notes+=p.events.length;runs++;}}assert.ok(signatures.size>20,id+' rhythm diversity');}
const motifSource={id:'chords',events:[]};for(let bar=0;bar<4;bar++)for(const tick of [0,480,960,1440])for(const midi of [60,63,67])motifSource.events.push({tick:bar*1920+tick,dur:300,midi,vel:90});const motif=rhythmVariation(motifSource,4,'phrase-test','explore',steps,0);const relativeOnsets=bar=>[...new Set(motif.events.filter(e=>Math.floor(e.tick/1920)===bar).map(e=>e.tick%1920))];assert.deepEqual(relativeOnsets(0),relativeOnsets(2));
const segments=[{start:0,end:.4,midi:69},{start:.55,end:1,midi:72},{start:1.8,end:2.1,midi:76},{start:2.7,end:3,midi:77},{start:3.1,end:3.3,midi:81}];
for(const mode of ['follow','answer','support']){const result=guidedVocalParts(segments,['melody','chords','bass'],9,steps,120,.2,4,mode);assert.ok(result.parts.every(p=>p.events.every(e=>steps.includes((e.midi-9+120)%12))));const melody=result.parts.find(p=>p.id==='melody');if(mode==='follow')assert.ok(melody.events.every((e,i)=>Math.abs(e.tick/960-(segments[i].start+.2))<.002));if(mode==='answer')assert.ok(melody.events.every(e=>segments.every(s=>e.tick/960-.2>=s.end|| (e.tick+e.dur)/960-.2<=s.start)));}
const a=guidedVocalParts(segments,['melody','chords'],9,steps,120,0,4,'follow');const other=segments.map(s=>({...s,midi:s.midi+5}));const b=guidedVocalParts(other,['melody','chords'],9,steps,120,0,4,'follow');assert.notDeepEqual(a.parts[0].events,b.parts[0].events);assert.notDeepEqual(a.harmony,b.harmony);
const full=[{start:0,end:4,midi:69}];assert.equal(guidedVocalParts(full,['melody'],9,steps,120,0,4,'answer').parts[0].events.length,0);
const clip={meta:{bars:1},parts:[{id:'bass',events:[{tick:0,dur:480,midi:44,vel:90}]},{id:'chords',events:[{tick:0,dur:1920,midi:60,vel:90},{tick:0,dur:1920,midi:64,vel:90},{tick:0,dur:1920,midi:67,vel:90}]},{id:'kick',events:[{tick:0,dur:60,midi:36,vel:90}]}]};const linked=relateParts(structuredClone(clip),['bass'],'space',{});assert.equal(linked.parts[0].events[0].midi%12,0);assert.ok(linked.parts[0].events[0].midi>=28&&linked.parts[0].events[0].midi<=52);assert.equal(linked.parts[0].events[0].tick,120);assert.deepEqual(relateParts(structuredClone(clip),['bass'],'space',{bass:true}),clip);
// Chord inversions still resolve to their harmonic root and preserve a usable bass register.
const inverted={meta:{bars:1},parts:[{id:'bass',events:[{tick:240,dur:360,midi:47,vel:90}]},{id:'chords',events:[{tick:0,dur:1920,midi:64,vel:80},{tick:0,dur:1920,midi:67,vel:80},{tick:0,dur:1920,midi:72,vel:80}]}]};const rooted=relateParts(structuredClone(inverted),['bass'],'follow',{});assert.equal(rooted.parts[0].events[0].midi%12,0);assert.ok(Math.abs(rooted.parts[0].events[0].midi-47)<=6);
// Unsorted, overlapping and malformed vocal segments cannot create notes inside occupied gaps or crash analysis.
const rough=[{start:1.1,end:1.5,midi:72},{start:.2,end:.8,midi:69},{start:.7,end:1.2,midi:71},{start:2,end:1,midi:70},{start:NaN,end:2,midi:70}];const roughAnswer=guidedVocalParts(rough,['melody'],9,steps,120,0,2,'answer').parts[0].events;const occupied=[[.2,1.5]];assert.ok(roughAnswer.every(e=>occupied.every(([s,f])=>e.tick/960>=f||(e.tick+e.dur)/960<=s)));
const emptyAnswer=guidedVocalParts([],['melody'],9,steps,0,-2,1,'answer').parts[0].events;assert.ok(emptyAnswer.length>0);assert.ok(emptyAnswer.every(e=>Number.isInteger(e.tick)&&e.tick>=0&&e.dur>0&&steps.includes((e.midi-9+120)%12)));
console.log(JSON.stringify({status:'PASS',runs,notes,instruments:ids.length,checks:'determinism, rhythm diversity, alternating-bar motif coherence, integer bounds, scale, source-dependent melody/harmony, robust gap-only answers, inversion-aware bass roots, locks, kick/bass spacing'},null,2));
