const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));const ok=(v,m)=>{assert.ok(v,m);checks.push(m);};const out=process.env.QA_OUTPUT||path.resolve('test-results');fs.mkdirSync(out,{recursive:true});await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.locator('#projectName').fill('Studio take 24');await p.locator('#projectName').dispatchEvent('change');await p.locator('#reroll').click();await p.locator('[data-lock="bass"]').click();const before=await p.evaluate(()=>JSON.stringify(current.parts.map(p=>p.events)));await p.waitForFunction(()=>localStorage.getItem(RECOVERY_KEY)?.includes('Studio take 24'));const data=await p.evaluate(()=>projectPayload());const dl=await Promise.all([p.waitForEvent('download'),p.locator('#saveProject').click()]);const file=await dl[0].path();const downloaded=JSON.parse(fs.readFileSync(file,'utf8'));ok(downloaded.name==='Studio take 24','project name exported');ok(downloaded.session.state.x.session.locks.bass,'locks in project');ok(JSON.stringify(downloaded.session.clip.parts.map(p=>p.events))===before,'exact events exported');
 await p.reload();ok(await p.locator('#recoveryBanner').isVisible(),'previous session offered after reload');const stored=await p.evaluate(()=>localStorage.getItem(RECOVERY_KEY));await p.locator('#reroll').click();await p.waitForTimeout(600);ok(await p.evaluate(()=>localStorage.getItem(RECOVERY_KEY))===stored,'pending recovery is not overwritten');await p.locator('#recoverProject').click();ok(await p.evaluate(()=>JSON.stringify(current.parts.map(p=>p.events)))===before,'recovery restores exact events');ok(await p.locator('#projectName').inputValue()==='Studio take 24','recovery restores project name');ok(await p.evaluate(()=>sessionConfig.locks.bass),'recovery restores lock');ok(await p.evaluate(()=>!vocalLinked),'recovery never attaches vocal audio');
 await p.locator('#unlockAll').click();await p.locator('#reroll').click();await p.evaluate(()=>sessionMessage(''));await p.locator('#projectFile').setInputFiles({name:'session.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await p.waitForFunction(()=>$('sessionNotice').textContent.startsWith('Project geopend'));ok(await p.evaluate(()=>JSON.stringify(current.parts.map(p=>p.events)))===before,'project import restores exact events');
 await p.locator('#unlockAll').click();await p.locator('#reroll').click();
 await p.waitForFunction(()=>JSON.stringify(JSON.parse(localStorage.getItem(RECOVERY_KEY)).session.clip)===JSON.stringify(current));
 await p.locator('#undoTake').click();await p.waitForTimeout(650);
 ok(await p.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem(RECOVERY_KEY)).session.clip)===JSON.stringify(current)),'undo updates local recovery');
 await p.locator('#redoTake').click();await p.waitForTimeout(650);
 ok(await p.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem(RECOVERY_KEY)).session.clip)===JSON.stringify(current)),'redo updates local recovery');
 const frozen=await p.evaluate(()=>JSON.stringify(current));await p.locator('#projectFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"unknown"}')});await p.waitForFunction(()=>$('projectStatus').textContent.includes('niet geopend'));ok(await p.evaluate(()=>JSON.stringify(current))===frozen,'invalid import preserves current session');
 const tampered=structuredClone(data);tampered.session.clip.meta.scale={steps:['oops'],name:'bad'};await p.evaluate(()=>sessionMessage(''));await p.locator('#projectFile').setInputFiles({name:'scale.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(tampered))});await p.waitForFunction(()=>$('sessionNotice').textContent.startsWith('Project geopend'));await p.waitForFunction(()=>current.meta.scale.steps.every(Number.isFinite));await p.locator('#unlockAll').click();await p.locator('#reroll').click();ok(await p.evaluate(()=>current.parts.every(p=>p.events.every(e=>Number.isFinite(e.midi)))),'malformed scale normalized before variation');
 let actions=0;for(let i=0;i<120;i++){await p.evaluate(i=>{if(i%12===0)selectView('generator');const id=PART_ORDER[i%PART_ORDER.length];if(i%5===0){const cb=document.querySelector('[data-part="'+id+'"]');cb.checked=true;cb.dispatchEvent(new Event('change',{bubbles:true}));}else if(i%5===1)varySession(id);else if(i%5===2)$('undoTake').click();else if(i%5===3)$('redoTake').click();else {selectInstrument(id);$('inspectorLock').click();$('unlockAll').click();}},i);actions++;}ok(await p.evaluate(()=>current.parts.every(p=>p.events.every(e=>Number.isInteger(e.tick)&&e.tick>=0&&e.dur>0&&e.tick+e.dur<=current.meta.bars*1920))),'120 session actions retain valid note bounds');
 for(const width of [1440,1024,390]){await p.setViewportSize({width,height:1000});await p.evaluate(()=>document.body.classList.add('inspector-closed'));ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'project row fits '+width);await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,'project-'+width+'.png'),fullPage:true});}
 const emptySource=structuredClone(data);emptySource.session.source.parts=[];ok(await p.evaluate(raw=>cleanProject(raw).session.source.parts.length>0,emptySource),'empty arrangement source falls back to clip');await p.evaluate(()=>localStorage.setItem(RECOVERY_KEY,'broken JSON'));await p.reload();ok(await p.locator('#recoveryBanner').isVisible(),'corrupt recovery offers explicit restart');ok(await p.locator('#recoverProject').isDisabled(),'unreadable recovery cannot be restored');await p.locator('#discardRecovery').click();await p.waitForFunction(()=>{try{return JSON.parse(localStorage.getItem(RECOVERY_KEY)).version===1}catch(e){return false}});ok(await p.evaluate(()=>!recoveryBlocked),'restart resumes autosave');ok(errors.length===0,'no runtime errors');const report={status:'PASS',checks:checks.length,stressActions:actions,results:checks,errors};fs.writeFileSync(path.join(out,'projects-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
