const assert=require('assert/strict'),fs=require('fs');const {analyseVocal,vocalMelodyEvents}=require('../src/vocal-engine');
const sr=8000,notes=[69,72,76,74,72,71,69,64,67,69,72,76,69];let cursor=.2;const truth=notes.map((m,i)=>{const dur=[.32,.48,.27,.6][i%4],n={midi:m,start:cursor,end:cursor+dur};cursor+=dur+.13;return n;});const samples=new Float32Array(Math.ceil((cursor+.2)*sr));
for(const n of truth)for(let i=Math.ceil(n.start*sr);i<n.end*sr;i++){const t=i/sr-n.start,len=n.end-n.start,env=Math.min(1,t/.02,(len-t)/.03),phase=2*Math.PI*440*2**((n.midi-69)/12)*t;samples[i]=.24*env*(Math.sin(phase)+.35*Math.sin(phase*2)+.12*Math.sin(phase*3));}
const a=analyseVocal(samples,sr);assert(a.segments.length>=notes.length-2,'detect distinct notes');let accurate=0;for(const n of truth){const found=a.segments.find(s=>Math.abs(s.start-n.start)<.13&&s.midi===n.midi);if(found)accurate++;}assert(accurate>=notes.length-2,'pitch and onset accuracy');assert(a.keys.some(k=>k.root===9&&k.scale==='aeolian'),'A minor in candidate keys');assert(!analyseVocal(new Float32Array(sr*2)).segments.length,'silence rejected');
const melody=vocalMelodyEvents(a.segments,9,[0,2,3,5,7,8,10],130,.25);for(let i=0;i<melody.length;i++){assert(Math.abs(melody[i].tick/480*60/130-(a.segments[i].start+.25))<.001,'rhythm retained in seconds');assert([0,2,3,5,7,8,10].includes((melody[i].midi-9+120)%12),'in key');}
assert(vocalMelodyEvents(a.segments,9,[0,2,3,5,7,8,10],130,0,'space').length<melody.length,'space mode reduces density');
// Deterministic synthetic, vocal-like harmonic signal, not a recording of a singer.
const wav=Buffer.alloc(44+samples.length*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(sr,24);wav.writeUInt32LE(sr*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(samples.length*2,40);samples.forEach((v,i)=>wav.writeInt16LE(Math.round(v*32767),44+i*2));fs.writeFileSync(process.env.VOCAL_FIXTURE||require('os').tmpdir()+'/midiroom-vocal-test.wav',wav);
console.log(JSON.stringify({status:'PASS',truthNotes:notes.length,matchedPitchAndOnsets:accurate,segments:a.segments.length,topKeys:a.keys,certainty:a.certainty,fixture:'synthetic harmonic tone sequence; no real singer validation'},null,2));
