/* Discovery Lab: compare forks without overwriting the working session. */
let discoverySource=null,discoveryCandidates=[],discoveryFingerprint='',discoveryAudition=null;
const DISCOVERY_RECIPES=[['source','Origineel','Je huidige loop als referentie.','#9aaec4'],['space','Meer ruimte','Rustpunten en kortere antwoorden.','#85d6c3'],['drive','Meer drive','Ritmische verdichting en korte herhalingen.','#efa76f'],['evolve','Meer verhaal','Terugkerend motief met veranderende frase-einden.','#b4a3ed']];
const lab=document.createElement('details');lab.id='discoveryLab';lab.innerHTML='<summary>'+icon('vary')+' Discovery Lab <span>Vergelijk · combineer · ontdek</span></summary><div class="discovery-body"><div class="discovery-heading"><div><h2>Eén idee. Drie nieuwe richtingen.</h2><p>Luister eerst. Kies daarna een hele versie of combineer je favoriete tracks.</p></div><button id="discoverNow" class="primary">Maak richtingen</button></div><p id="discoveryStatus" role="status">Begin met een loop van maximaal 32 maten. Locks blijven behouden.</p><div id="discoveryCards"></div><details id="discoveryBlend" hidden><summary>Combineer tracks uit de richtingen</summary><div id="discoveryBlendTracks"></div><div class="action-row"><button id="previewBlend">▶ Luister naar combinatie</button><button id="applyBlend" class="primary">Gebruik combinatie</button></div></details><details class="rhythm-transfer"><summary>Ritme lenen van een andere track</summary><p>Neem de aanzetten van bijvoorbeeld je lead over in de akkoorden. De doeltrack behoudt zijn eigen toonmateriaal.</p><div class="transfer-controls"><label>Ritme van<select id="rhythmDonor"></select></label><span>→</span><label>Toonmateriaal van<select id="rhythmTarget"></select></label><button id="previewTransfer">▶ Luister</button><button id="applyTransfer">Gebruik ritme</button></div></details><p class="hint">Preview gebruikt je huidige klanken en mixer. Kies Gebruik om MIDI te wijzigen; Undo zet je vorige versie terug. Vrije ritmeveranderingen kunnen afwijken van de vocal.</p></div>';
document.querySelector('.rollbox').before(lab);
function discoveryKey(){return current?JSON.stringify({parts:current.parts.map(p=>[p.id,p.events]),meta:current.meta,bpm:current.bpm,locks:sessionConfig.locks}):'';}
function labMessage(s){$('discoveryStatus').textContent=s;}
function labCurrent(){if(discoveryFingerprint&&discoveryKey()===discoveryFingerprint)return true;labMessage('Je sessie of locks zijn veranderd. Maak opnieuw richtingen voor deze versie.');return false;}
function discoveryMetric(clip){const n=clip.parts.reduce((n,p)=>n+p.events.length,0);const onsets=new Set(clip.parts.flatMap(p=>p.events.map(e=>e.tick)));return n+' noten · '+onsets.size+' aanzetten';}
function discoveryMini(clip){const width=320,height=65,total=clip.meta.bars*1920;return '<svg viewBox="0 0 '+width+' '+height+'" role="img" aria-label="Ritmeverdeling van deze versie">'+clip.parts.map((p,i)=>p.events.filter((_,j)=>j%Math.max(1,Math.ceil(p.events.length/100))===0).map(e=>'<rect x="'+(e.tick/total*width).toFixed(1)+'" y="'+(5+i*(55/Math.max(1,clip.parts.length))).toFixed(1)+'" width="'+Math.max(1,e.dur/total*width).toFixed(1)+'" height="3" fill="'+PART_DEFS[p.id].colour+'"/>').join('')).join('')+'</svg>';}
function renderDiscoveryCards(){
 $('discoveryCards').innerHTML=discoveryCandidates.map((clip,i)=>'<article class="discovery-card" style="--recipe:'+DISCOVERY_RECIPES[i][3]+'"><span class="eyebrow">'+String(i+1).padStart(2,'0')+' / '+(i?'RICHTING':'BRON')+'</span><h3>'+DISCOVERY_RECIPES[i][1]+'</h3><p>'+DISCOVERY_RECIPES[i][2]+'</p>'+discoveryMini(clip)+'<small>'+discoveryMetric(clip)+'</small><div><button data-listen-discovery="'+i+'">▶ Luister</button><button data-use-discovery="'+i+'">Gebruik</button></div></article>').join('');
 $('discoveryBlend').hidden=!discoverySource;$('discoveryBlendTracks').innerHTML=(discoverySource?.parts||[]).map(p=>'<label class="blend-track"><span style="color:'+PART_DEFS[p.id].colour+'">'+p.label+'</span><select data-blend-track="'+p.id+'" '+(sessionConfig.locks[p.id]?'disabled':'')+'>'+DISCOVERY_RECIPES.map((r,i)=>'<option value="'+i+'">'+r[1]+(sessionConfig.locks[p.id]&&i===0?' · vastgezet':'')+'</option>').join('')+'</select></label>').join('');
}
$('discoverNow').onclick=()=>{if(!current||current.meta.bars>32||current.parts.reduce((n,p)=>n+p.events.length,0)>20000){labMessage('Kies een loop van 1–32 maten en maximaal 20.000 noten voor het Lab.');return;}discoverySource=clone(current);discoveryFingerprint=discoveryKey();const seed=newSeed();discoveryCandidates=DISCOVERY_RECIPES.map((r,i)=>i?discoverClip(discoverySource,r[0],seed,sessionConfig.locks):clone(discoverySource));renderDiscoveryCards();labMessage('Drie richtingen klaar. Luisteren verandert je opgeslagen sessie niet.');};
const stopBeforeDiscovery=stopAudio;
stopAudio=function(){const audition=discoveryAudition;discoveryAudition=null;stopBeforeDiscovery();if(audition){current=audition.clip;vocalLinked=audition.linked;$('loop').checked=audition.loop;rollCache=null;drawRoll();refreshWorkspace();scheduleRecovery();labMessage('Preview gestopt. Je oorspronkelijke sessie staat terug.');}};
function listenDiscovery(clip,label){
 stopAudio();clearTimeout(recoveryTimer);const original={clip:current,linked:vocalLinked,loop:$('loop').checked};
 current=clone(clip);vocalLinked=false;$('loop').checked=false;
 try{playAll();if(!playing){current=original.clip;vocalLinked=original.linked;$('loop').checked=original.loop;drawRoll();return;}discoveryAudition=original;labMessage('Preview: '+label+' · alleen MIDI · Stop of Spatie keert terug naar je sessie.');}catch(e){current=original.clip;vocalLinked=original.linked;$('loop').checked=original.loop;stopBeforeDiscovery();labMessage('Preview niet beschikbaar: '+e.message);}
}
// No autosave or keyboard/UI action may accidentally capture a temporary audition.
const projectBeforeDiscovery=projectPayload;projectPayload=function(){if(!discoveryAudition)return projectBeforeDiscovery();const payload=projectBeforeDiscovery();payload.session.clip=discoveryAudition.clip;return payload;};
const rememberBeforeDiscovery=rememberTake;rememberTake=function(){if(!discoveryAudition)rememberBeforeDiscovery();};
document.addEventListener('click',()=>{if(discoveryAudition)stopAudio();},true);
document.addEventListener('keydown',e=>{if(!discoveryAudition)return;stopAudio();if(e.code==='Space'){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('input',()=>{if(discoveryAudition)stopAudio();},true);
function useDiscovery(clip,message){stopAudio();if(!labCurrent())return;const next=clone(clip);next.customEdit=true;if(next.vocalSourceSerial!==vocalSourceSerial)vocalLinked=false;finishSession(next,message+' · Undo herstelt je vorige sessie.');discoveryFingerprint='';}
$('discoveryCards').onclick=e=>{const listen=e.target.closest('[data-listen-discovery]'),use=e.target.closest('[data-use-discovery]');if(listen&&labCurrent())listenDiscovery(discoveryCandidates[+listen.dataset.listenDiscovery],DISCOVERY_RECIPES[+listen.dataset.listenDiscovery][1]);if(use)useDiscovery(discoveryCandidates[+use.dataset.useDiscovery],DISCOVERY_RECIPES[+use.dataset.useDiscovery][1]+' gekozen');};
function blendDiscovery(){const clip=clone(discoverySource);clip.parts=clip.parts.map(p=>{const choice=Number(document.querySelector('[data-blend-track="'+p.id+'"]').value);return clone(discoveryCandidates[sessionConfig.locks[p.id]?0:choice].parts.find(x=>x.id===p.id));});clip.customEdit=true;if([...document.querySelectorAll('[data-blend-track]')].some(s=>Number(s.value)!==0)){clip.vocalTiming=false;delete clip.vocalSourceSerial;}return clip;}
$('previewBlend').onclick=()=>{if(labCurrent())listenDiscovery(blendDiscovery(),'Je combinatie');};$('applyBlend').onclick=()=>{if(labCurrent())useDiscovery(blendDiscovery(),'Tracks gecombineerd');};
function transferCandidate(){const donor=$('rhythmDonor').value,target=$('rhythmTarget').value;if(!current||donor===target){labMessage('Kies twee verschillende tracks.');return null;}if(sessionConfig.locks[target]){labMessage('Ontgrendel de doeltrack om zijn ritme te veranderen.');return null;}return transplantRhythm(current,donor,target,sessionConfig.locks);}
$('previewTransfer').onclick=()=>{const c=transferCandidate();if(c)listenDiscovery(c,'Geleend ritme');};$('applyTransfer').onclick=()=>{const c=transferCandidate();if(c){if(c.vocalSourceSerial!==vocalSourceSerial)vocalLinked=false;finishSession(c,'Ritme overgenomen. Andere tracks zijn behouden.');}};
const renderBeforeDiscovery=renderSession;renderSession=function(){renderBeforeDiscovery();['rhythmDonor','rhythmTarget'].forEach(id=>{const el=$(id),old=el.value;el.innerHTML=(current?.parts||[]).map(p=>'<option value="'+p.id+'">'+p.label+'</option>').join('');if([...el.options].some(o=>o.value===old))el.value=old;else if(id==='rhythmTarget'&&el.options.length>1)el.selectedIndex=1;});$('discoverNow').disabled=!current;};
