const {chromium}=require('playwright'),path=require('path'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1440,height:1000}}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const ok=(v,m)=>{assert.ok(v,m);checks.push(m)};const out=process.env.QA_OUTPUT||path.resolve('test-results');fs.mkdirSync(out,{recursive:true});await p.goto('file://'+path.resolve(__dirname,'../index.html'));
 ok(await p.locator('#performanceMode').inputValue()==='natural','fresh sessions default to natural feel');
 await p.locator('#genreSelect').selectOption('italo');await p.locator('[data-lock="bass"]').click();const bass=await p.evaluate(()=>JSON.stringify(current.parts.find(p=>p.id==='bass')));const initial=await p.evaluate(()=>JSON.stringify(current.parts));
 await p.locator('#performanceMode').selectOption('bold');ok(await p.evaluate(()=>JSON.stringify(current.parts))===initial,'mode selection leaves existing notes unchanged');
 await p.locator('#performNow').click();ok(await p.evaluate(()=>JSON.stringify(current.parts))!==initial,'manual expression changes MIDI');ok(await p.evaluate(()=>JSON.stringify(current.parts.find(p=>p.id==='bass')))===bass,'manual expression respects locked bass');const expressed=await p.evaluate(()=>JSON.stringify(current.parts));
 await p.locator('#undoTake').click();ok(await p.evaluate(()=>JSON.stringify(current.parts))===initial,'undo restores exact pre-expression MIDI');await p.locator('#redoTake').click();ok(await p.evaluate(()=>JSON.stringify(current.parts))===expressed,'redo restores expressive MIDI');
 ok(await p.evaluate(()=>cleanProject(projectPayload()).session.state.x.session.performance)==='bold','feel setting survives project sanitizer');
 await p.locator('#reroll').click();ok(await p.evaluate(()=>JSON.stringify(current.parts.find(p=>p.id==='bass')))===bass,'generation preserves locked bass');
 await p.locator('#performanceMode').selectOption('off');ok(await p.locator('#performNow').isDisabled(),'off disables expression action');await p.locator('#performanceMode').selectOption('pocket');
 for(let i=0;i<24;i++){await p.locator('#performNow').click();}ok(await p.evaluate(()=>current.parts.every(p=>p.events.every(e=>Number.isInteger(e.tick)&&e.tick>=0&&e.dur>0&&e.tick+e.dur<=current.meta.bars*1920))),'24 expressive passes keep valid MIDI');
 for(const width of [1440,390]){await p.setViewportSize({width,height:1000});await p.evaluate(()=>document.body.classList.add('inspector-closed'));ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'performance bar fits '+width);await p.screenshot({path:path.join(out,'expression-'+width+'.png'),fullPage:true});}
 ok(errors.length===0,'no runtime errors');const report={status:'PASS',checks:checks.length,stressActions:24,results:checks,errors};fs.writeFileSync(path.join(out,'expression-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
