const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const be=(n,l)=>Array.from({length:l},(_,i)=>(n>>(8*(l-i-1)))&255),vlq=n=>{let a=[n&127];while(n>>=7)a.unshift((n&127)|128);return a;},chunk=(s,a)=>[...Buffer.from(s),...be(a.length,4),...a];
function midi(){const ev=[0,255,3,5,...Buffer.from('SWING'),0,255,81,3,7,161,32,120,0x90,36,72,...vlq(120),0x80,36,0,...vlq(300),0x90,38,117,...vlq(210),0x80,38,0,...vlq(330),0x90,40,91,...vlq(90),0x80,40,0,0,255,47,0],head=chunk('MThd',[0,0,0,1,1,224]);return Buffer.from([...head,...chunk('MTrk',ev)]);}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,m)=>{assert.ok(v,m);checks.push(m);},out=process.env.QA_OUTPUT||path.resolve('test-results/groove');fs.mkdirSync(out,{recursive:true});await page.goto('file://'+path.resolve(__dirname,'../index.html'));await page.evaluate(()=>applyGenre('disco',false));
ok(await page.locator('#grooveDNA').count()===1,'Groove DNA panel available');await page.locator('#studioTool-groove').click();await page.locator('#grooveFile').setInputFiles({name:'own-groove.mid',mimeType:'audio/midi',buffer:midi()});await page.waitForFunction(()=>!$('grooveControls').hidden);ok(await page.locator('#grooveTrack option').count()===1,'imported MIDI track analyzed');ok((await page.locator('#grooveFileMeta').innerText()).includes('120 BPM'),'MIDI tempo displayed');ok((await page.locator('#grooveFileMeta').innerText()).includes('3 noten'),'note count displayed');
ok((await page.locator('#grooveStatus').innerText()).includes('MIDIROOM-sessie'),'session tempo behavior is explicit');ok((await page.locator('#grooveStatus').innerText()).includes('PPQ-groove'),'source tempo is not presented as playback tempo');
await page.evaluate(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){return this.name==='slow.mid'?new Promise(resolve=>setTimeout(()=>original.call(this).then(resolve),120)):original.call(this);};});await page.locator('#grooveFile').setInputFiles({name:'slow.mid',mimeType:'audio/midi',buffer:midi()});await page.locator('#grooveFile').setInputFiles({name:'fast.mid',mimeType:'audio/midi',buffer:midi()});await page.waitForTimeout(180);ok((await page.locator('#grooveFileMeta').innerText()).includes('fast.mid'),'latest async MIDI selection wins');
await page.locator('#grooveTarget').selectOption('chords');const before=await page.evaluate(()=>JSON.stringify(current));const chordPitches=await page.evaluate(()=>[...new Set(current.parts.find(p=>p.id==='chords').events.map(e=>e.midi))].sort((a,b)=>a-b));await page.locator('#grooveListen').click();ok(await page.evaluate(()=>playing&&!!discoveryAudition),'groove can be previewed through current sounds');await page.evaluate(()=>stopAudio());ok(await page.evaluate(x=>JSON.stringify(current)===x,before),'stopping preview restores exact session');
await page.locator('#grooveApply').click();const afterPitches=await page.evaluate(()=>[...new Set(current.parts.find(p=>p.id==='chords').events.map(e=>e.midi))].sort((a,b)=>a-b));ok(afterPitches.every(n=>chordPitches.includes(n)),'groove transfer preserves target pitch material');ok(await page.evaluate(()=>current.parts.find(p=>p.id==='chords').events.some(e=>e.tick===120)),'donor timing applied');ok(await page.evaluate(()=>current.parts.find(p=>p.id==='chords').events.some(e=>e.vel===117)),'donor accents applied');await page.locator('#undoTake').click();ok(await page.evaluate(x=>JSON.stringify(current)===x,before),'groove apply supports exact undo');
const otherBefore=await page.evaluate(()=>JSON.stringify(current.parts.filter(p=>p.id!=='bass').map(p=>p.events)));await page.locator('#grooveTarget').selectOption('bass');await page.locator('#grooveImport').click();ok(await page.evaluate(()=>current.parts.find(p=>p.id==='bass').events.length===3),'MIDI can replace chosen track');ok(await page.evaluate(x=>JSON.stringify(current.parts.filter(p=>p.id!=='bass').map(p=>p.events))===x,otherBefore),'track import preserves every other instrument');ok((await page.locator('#grooveStatus').innerText()).includes('zonder timestretch'),'import behavior is explicit');
await page.locator('[data-lock="bass"]').click();const locked=await page.evaluate(()=>JSON.stringify(current.parts.find(p=>p.id==='bass').events));await page.locator('#grooveImport').click();ok(await page.evaluate(x=>JSON.stringify(current.parts.find(p=>p.id==='bass').events)===x,locked),'locked target cannot be replaced');ok((await page.locator('#grooveStatus').innerText()).includes('Ontgrendel'),'locked target gives clear feedback');
await page.locator('#grooveFile').setInputFiles({name:'broken.mid',mimeType:'audio/midi',buffer:Buffer.from([1,2,3])});await page.waitForFunction(()=>$('grooveControls').hidden);ok((await page.locator('#grooveStatus').innerText()).includes('geen volledige MIDI'),'malformed MIDI rejected clearly');ok(await page.locator('#grooveControls').isHidden(),'failed load cannot reuse previous donor');for(const width of [1024,390]){await page.setViewportSize({width,height:900});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Groove DNA fits '+width);await page.screenshot({path:path.join(out,'groove-'+width+'.png'),fullPage:true});}ok(errors.length===0,'no runtime errors');const report={status:'PASS',checks:checks.length,results:checks,errors};fs.writeFileSync(path.join(out,'groove-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
