/* Phrase Sculptor: edit one exact bar range while the rest of the session remains untouched. */
let sculptCandidates=[],sculptFingerprint='',sculptDragStart=null;
const SCULPT_ACTIONS={space:['Meer ruimte','Snijdt gerichte aanzetten weg en maakt korte ademgaten.'],tension:['Meer spanning','Tilt geselecteerde tonen en maakt het einde dringender.'],answer:['Maak antwoord','Vormt de frase tot een afwisselend muzikaal antwoord.'],broken:['Breek ritme','Splitst noten binnen hun bestaande ruimte tot een onverwacht ritme.']};
const sculpt=document.createElement('details');sculpt.id='phraseSculptor';sculpt.open=true;sculpt.innerHTML='<summary>'+icon('vary')+' Phrase Sculptor <span>Bewerk alleen je selectie</span></summary><div class="sculpt-body"><div class="sculpt-controls"><label>Track<select id="sculptTrack"></select></label><label>Van maat<input id="sculptStart" type="number" min="1" value="1"></label><label>Tot maat<input id="sculptEnd" type="number" min="1" value="2"></label><label>Richting<select id="sculptAction">'+Object.entries(SCULPT_ACTIONS).map(([id,a])=>'<option value="'+id+'">'+a[0]+'</option>').join('')+'</select></label><button id="sculptMake" class="primary">Maak 3 takes</button></div><p id="sculptHint" class="hint">Sleep over de piano roll of vul maten in. Noten die over een selectierand lopen blijven exact staan.</p><div id="sculptCards"></div></div>';
$('rollViewport').before(sculpt);
const sculptOverlay=document.createElement('div');sculptOverlay.id='sculptSelectionOverlay';sculptOverlay.setAttribute('aria-hidden','true');$('rollViewport').appendChild(sculptOverlay);
function sculptKey(){return current?JSON.stringify({parts:current.parts.map(p=>[p.id,p.events]),meta:current.meta,bpm:current.bpm,locks:sessionConfig.locks}):'';}
function sculptMessage(s){$('sculptHint').textContent=s;}
function sculptRange(){const bars=Math.max(1,current?.meta?.bars||1),start=Math.max(1,Math.min(bars,Math.floor(+$('sculptStart').value||1))),end=Math.max(start,Math.min(bars,Math.floor(+$('sculptEnd').value||start)));$('sculptStart').value=start;$('sculptEnd').value=end;return {start,end};}
function sculptActive(){return sculpt.open&&sculpt.getClientRects().length>0;}
function drawSculptSelection(){if(!current||!rollMap||!sculptActive()){sculptOverlay.hidden=true;return;}const r=sculptRange(),span=rollMap.W-52,x1=48+((r.start-1)*1920/rollMap.totalTicks)*span,x2=48+(r.end*1920/rollMap.totalTicks)*span;sculptOverlay.hidden=false;sculptOverlay.style.left=x1+'px';sculptOverlay.style.width=Math.max(2,x2-x1)+'px';sculptOverlay.dataset.label='Maat '+r.start+'–'+r.end;}
function renderSculptTracks(){const el=$('sculptTrack'),old=el.value||selectedInstrument;el.innerHTML=(current?.parts||[]).map(p=>'<option value="'+p.id+'" '+(sessionConfig.locks[p.id]?'disabled':'')+'>'+p.label+(sessionConfig.locks[p.id]?' · locked':'')+'</option>').join('');if([...el.options].some(o=>o.value===old&&!o.disabled))el.value=old;else{const first=[...el.options].find(o=>!o.disabled);if(first)el.value=first.value;}const available=[...el.options].some(o=>!o.disabled);$('sculptMake').disabled=!current||!available;const bars=Math.max(1,current?.meta?.bars||1);$('sculptStart').max=bars;$('sculptEnd').max=bars;sculptRange();drawSculptSelection();}
function renderSculptCards(){const action=$('sculptAction').value;$('sculptCards').innerHTML=sculptCandidates.map((c,i)=>'<article class="sculpt-card"><span class="eyebrow">TAKE '+(i+1)+'</span><strong>'+SCULPT_ACTIONS[action][0]+'</strong><small>'+SCULPT_ACTIONS[action][1]+'</small><div><button data-sculpt-listen="'+i+'">▶ Luister</button><button data-sculpt-use="'+i+'" class="primary">Gebruik</button></div></article>').join('');}
$('sculptMake').onclick=()=>{if(!current)return;const partId=$('sculptTrack').value;if(!partId){sculptMessage('Alle tracks staan vast. Ontgrendel minstens één track.');return;}if(sessionConfig.locks[partId]){sculptMessage('Deze track staat vast. Ontgrendel hem eerst.');return;}const r=sculptRange(),seed=newSeed();try{sculptCandidates=[0,1,2].map(i=>sculptPhrase(current,{partId,startBar:r.start,endBar:r.end,action:$('sculptAction').value,seed:seed+':'+i,locks:sessionConfig.locks}));sculptFingerprint=sculptKey();renderSculptCards();sculptMessage('Drie takes klaar voor maat '+r.start+'–'+r.end+'. Luisteren is tijdelijk; Gebruik maakt één Undo-stap.');}catch(e){sculptMessage(e.message);}};
$('sculptCards').onclick=e=>{const listen=e.target.closest('[data-sculpt-listen]'),use=e.target.closest('[data-sculpt-use]');if(!listen&&!use)return;if(!sculptFingerprint||sculptFingerprint!==sculptKey()){sculptMessage('De sessie is veranderd. Maak opnieuw takes voor deze versie.');return;}const i=Number((listen||use).dataset[listen?'sculptListen':'sculptUse']),clip=sculptCandidates[i];if(listen)listenDiscovery(clip,'Phrase Sculptor · take '+(i+1));else{stopAudio();const next=clone(clip);if(next.vocalSourceSerial!==vocalSourceSerial)vocalLinked=false;finishSession(next,'Phrase Sculptor toegepast op maat '+$('sculptStart').value+'–'+$('sculptEnd').value+'.');sculptFingerprint='';}};
['sculptStart','sculptEnd'].forEach(id=>$(id).addEventListener('input',()=>{sculptCandidates=[];$('sculptCards').innerHTML='';drawSculptSelection();}));
$('sculptAction').onchange=()=>{sculptCandidates=[];$('sculptCards').innerHTML='';sculptMessage(SCULPT_ACTIONS[$('sculptAction').value][1]);};
$('sculptTrack').onchange=()=>{sculptCandidates=[];$('sculptCards').innerHTML='';sculptMessage('Nieuwe track gekozen. Maak drie takes voor deze selectie.');};
function sculptBarAt(clientX){if(!current||!rollMap)return null;const rect=cv.getBoundingClientRect(),x=Math.max(48,Math.min(rollMap.W,clientX-rect.left)),tick=(x-48)/Math.max(1,rollMap.W-52)*rollMap.totalTicks;return Math.max(1,Math.min(current.meta.bars,Math.floor(tick/1920)+1));}
cv.addEventListener('pointerdown',e=>{if(e.button!==0||!current||!sculptActive())return;sculptDragStart=sculptBarAt(e.clientX);if(!sculptDragStart)return;try{cv.setPointerCapture?.(e.pointerId);}catch(_){}$('sculptStart').value=sculptDragStart;$('sculptEnd').value=sculptDragStart;drawSculptSelection();});
cv.addEventListener('pointermove',e=>{if(sculptDragStart==null)return;const bar=sculptBarAt(e.clientX);$('sculptStart').value=Math.min(sculptDragStart,bar);$('sculptEnd').value=Math.max(sculptDragStart,bar);drawSculptSelection();});
cv.addEventListener('pointerup',e=>{if(sculptDragStart==null)return;sculptDragStart=null;try{cv.releasePointerCapture?.(e.pointerId);}catch(_){}sculptCandidates=[];$('sculptCards').innerHTML='';sculptMessage('Selectie staat klaar. Kies een richting en maak drie takes.');});
cv.addEventListener('pointercancel',()=>{sculptDragStart=null;});
$('rollViewport').addEventListener('scroll',drawSculptSelection,{passive:true});
const drawBeforeSculpt=drawRoll;drawRoll=function(playhead){drawBeforeSculpt(playhead);drawSculptSelection();};
const renderBeforeSculpt=renderSession;renderSession=function(){renderBeforeSculpt();renderSculptTracks();};
