/* Vocal Conversation UI. Loaded after session + discovery. */
(function(){
'use strict';
const host=document.createElement('section');host.id='vocalConversation';host.className='vocal-conversation';host.innerHTML='<div class="conversation-head"><div><span class="eyebrow">VOCAL CONVERSATION</span><h3>Laat je MIDI luisteren</h3><p>De begeleiding reageert op echte zangactiviteit en gemeten stiltes.</p></div><div class="conversation-head-actions"><span id="conversationBadge" class="conversation-badge">Analyse nodig</span><button id="conversationOpenVocal">Vocal laden & analyseren</button></div></div><div id="conversationTimeline" class="conversation-timeline" aria-label="Zangactiviteit en vrije ruimte"></div><div class="conversation-controls"><label>Gedrag<select id="conversationMode"><option value="converse">Vraag & antwoord</option><option value="support">Rustig ondersteunen</option></select></label><label class="conversation-range"><span>Afstand tot vocal <b id="conversationAmount">72%</b></span><input id="conversationCloseness" type="range" min="0" max="100" value="72"><small>Vrijer ← → sterker reageren</small></label></div><div><span class="conversation-label">Tracks laten reageren</span><div id="conversationTargets" class="conversation-targets"></div></div><div id="conversationMismatch" class="conversation-mismatch" hidden><span>De BPM/key hierboven wijkt af van je sessie.</span><button id="conversationAlign">Stem analyse af op sessie</button></div><div class="action-row"><button id="conversationPreview">Preview MIDI</button><button id="conversationApply" class="primary">Pas gesprek toe</button></div><p id="conversationStatus" class="hint" role="status"></p>';
const tool=$('vocalContent').querySelector('.tool-grid');(tool||$('vocalContent')).after(host);
const conversationSupported=new Set(['bass','chords','pad','harmony','lead','melody','screech','darkmelody','pluck','arp']);
const melodic=id=>conversationSupported.has(id);
let conversationTargetChoice=null,conversationKnownTargets=new Set();
function scaleId(){return Object.keys(SCALES).find(id=>JSON.stringify(SCALES[id].steps)===JSON.stringify(current?.meta?.scale?.steps));}
function aligned(){return !!current&&Math.round(+$('vocalBpm').value)===Math.round(current.bpm)&&+$('vocalRoot').value===current.meta.root&&$('vocalScale').value===scaleId();}
function renderTimeline(){const seg=vocalAnalysis?.segments||[],duration=safelyVocalDuration();if(!seg.length||!duration){$('conversationTimeline').innerHTML='<span>Analyseer je vocal om zang en ruimte te zien.</span>';return;}const clean=sanitizeSegments(seg,duration),w=vocalWindows(clean,duration);$('conversationTimeline').innerHTML='<div class="conversation-lane">'+w.active.map(a=>'<i class="voice" style="left:'+a.start/duration*100+'%;width:'+(a.end-a.start)/duration*100+'%" title="Zang"></i>').join('')+w.gaps.map(a=>'<i class="rest" style="left:'+a.start/duration*100+'%;width:'+(a.end-a.start)/duration*100+'%" title="Vrije ruimte"></i>').join('')+'</div><div class="conversation-legend"><span><i class="voice"></i>Zang</span><span><i class="rest"></i>Antwoordruimte</span><b>'+w.gaps.length+' bruikbare pauzes</b></div>';}
function renderConversation(){const ready=!!vocalAnalysis?.segments?.length&&!!current,parts=(current?.parts||[]).filter(p=>melodic(p.id));if(parts.length){if(conversationTargetChoice===null)conversationTargetChoice=new Set();for(const p of parts)if(!conversationKnownTargets.has(p.id)&&!sessionConfig.locks[p.id])conversationTargetChoice.add(p.id);conversationKnownTargets=new Set(parts.map(p=>p.id));conversationTargetChoice=new Set([...conversationTargetChoice].filter(id=>parts.some(p=>p.id===id)));}renderTimeline();$('conversationTargets').innerHTML=parts.map(p=>'<label style="--track:'+p.colour+'"><input type="checkbox" data-conversation-target="'+p.id+'" '+(sessionConfig.locks[p.id]?'disabled':conversationTargetChoice.has(p.id)?'checked':'')+'><span>'+p.label+'</span>'+(sessionConfig.locks[p.id]?'<small>Vast</small>':'')+'</label>').join('')||'<span class="hint">Genereer eerst melodische tracks.</span>';$('conversationBadge').textContent=!vocalAnalysis?'Analyse nodig':!current?'MIDI nodig':aligned()?'Klaar om te reageren':'BPM/key controleren';$('conversationBadge').classList.toggle('ready',ready&&aligned());$('conversationMismatch').hidden=!ready||aligned();$('conversationPreview').disabled=!ready||!aligned();$('conversationApply').disabled=!ready||!aligned();}
function candidate(){const targets=[...document.querySelectorAll('[data-conversation-target]:checked')].map(x=>x.dataset.conversationTarget);if(!targets.length)throw new Error('Kies minstens één vrije track.');const mode=$('conversationMode').value,result=conversationClip(current,vocalAnalysis.segments,{mode,closeness:+$('conversationCloseness').value,targets,locks:sessionConfig.locks,offset:bound($('vocalOffset').value,0,30,0),root:current.meta.root,steps:current.meta.scale.steps});const clip=result.clip;clip.vocalSourceSerial=vocalSourceSerial;clip.vocalRevision=vocalRevision;clip.vocalOffset=bound($('vocalOffset').value,0,30,0);clip.vocalMode=mode==='converse'?'answer':'support';return clip;}
$('conversationOpenVocal').onclick=()=>{if(typeof selectView==='function')selectView('generator');$('vocalDrawer').open=true;$('vocalDrawer').scrollIntoView({block:'start'});};
$('conversationCloseness').oninput=()=>{$('conversationAmount').textContent=$('conversationCloseness').value+'%';};
$('conversationAlign').onclick=()=>{if(!current)return;$('vocalBpm').value=current.bpm;$('vocalRoot').value=current.meta.root;const id=scaleId();if(id){let option=[...$('vocalScale').options].find(o=>o.value===id);if(!option){option=new Option((SCALES[id].label||id)+' · sessie',id);option.dataset.sessionScale='true';$('vocalScale').add(option);}$('vocalScale').value=id;}renderConversation();$('conversationStatus').textContent='Analyse-instellingen volgen nu de sessie. Luister altijd of de geschatte key klopt.';};
$('conversationPreview').onclick=()=>{try{listenDiscovery(candidate(),'Vocal Conversation');$('conversationStatus').textContent='Alleen de aangepaste MIDI speelt. Stop herstelt je sessie.';}catch(e){$('conversationStatus').textContent=e.message;}};
$('conversationTargets').onchange=e=>{const id=e.target.dataset.conversationTarget;if(!id)return;if(e.target.checked)conversationTargetChoice.add(id);else conversationTargetChoice.delete(id);};
$('conversationApply').onclick=()=>{try{const clip=candidate();vocalLinked=!!vocalBuffer;if(vocalLinked)$('loop').checked=false;finishSession(clip,'Vocal Conversation toegepast · zangactiviteit en pauzes sturen de gekozen tracks.');renderConversation();$('conversationStatus').textContent='Toegepast. Undo herstelt de vorige versie.';}catch(e){$('conversationStatus').textContent=e.message;}};
['vocalBpm','vocalRoot','vocalScale'].forEach(id=>$(id).addEventListener('change',renderConversation));
const renderBeforeConversation=renderSession;renderSession=function(){renderBeforeConversation();renderConversation();};
const showBeforeConversation=showVocalAnalysis;showVocalAnalysis=function(){showBeforeConversation();renderConversation();};
renderConversation();
})();
