/* MIDIROOM production workspace. Included after workspace.js, before first generation. */
var sessionConfig={strength:'explore',relation:'space',locks:{}};
let mixer={},soundPatches={},arrSections=[],baseLoop=null;
let mixerBuses={},mixerNodes=[],undoHistory=[],historyIndex=-1,historyRestoring=false,takeA=null;
let vocalBuffer=null,vocalURL=null,vocalAnalysis=null,vocalWorker=null,vocalLoadId=0,vocalLinked=false;
function clone(x){return JSON.parse(JSON.stringify(x));}
function bound(v,min,max,def){return Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):def;}
const PATCHES={
 'Warm pluck':{wave:'sawtooth',cutoff:2200,resonance:1.2,attack:.008,release:.15,drive:0,detune:7},
 'Italo brass':{wave:'sawtooth',cutoff:3800,resonance:2,attack:.025,release:.22,drive:8,detune:12},
 'Reese bass':{wave:'sawtooth',cutoff:850,resonance:1,attack:.01,release:.12,drive:25,detune:18},
 'Soft pad':{wave:'triangle',cutoff:2400,resonance:.7,attack:.3,release:.7,drive:0,detune:9},
 'Acid pulse':{wave:'square',cutoff:1300,resonance:7,attack:.003,release:.09,drive:20,detune:0},
 'Screech sketch':{wave:'sawtooth',cutoff:5500,resonance:5,attack:.004,release:.09,drive:60,detune:23}
};
function cleanPatch(p={}){return {wave:['sine','triangle','sawtooth','square'].includes(p.wave)?p.wave:'sawtooth',cutoff:bound(p.cutoff,80,12000,2200),resonance:bound(p.resonance,.1,12,1),attack:bound(p.attack,.003,1,.01),release:bound(p.release,.02,1.5,.2),drive:bound(p.drive,0,100,0),detune:bound(p.detune,0,35,7)};}
function cleanStudioState(x={}){
  if(!x||typeof x!=='object')x={};const mix={},patches={};
  PART_ORDER.forEach(id=>{mix[id]={volume:bound(x.mixer?.[id]?.volume,0,100,80),pan:bound(x.mixer?.[id]?.pan,-100,100,0)};if(x.patches?.[id])patches[id]=cleanPatch(x.patches[id]);});
  const sections=Array.isArray(x.sections)?x.sections.slice(0,16).map(s=>({name:String(s.name||'Sectie').slice(0,30),bars:Math.round(bound(s.bars,1,32,8)),gain:bound(s.gain,.2,1.2,1),variation:['subtle','explore','wild'].includes(s.variation)?s.variation:'same',transition:['breath','roll'].includes(s.transition)?s.transition:'none',parts:Array.isArray(s.parts)?s.parts.filter(id=>PART_ORDER.includes(id)):[]})):[];
  return {mixer:mix,patches,sections,session:cleanSessionConfig(x.session)};
}
function studioState(){return {mixer:clone(mixer),patches:clone(soundPatches),sections:clone(arrSections),session:clone(sessionConfig)};}
function restoreStudioState(x){const s=cleanStudioState(x);mixer=s.mixer;soundPatches=s.patches;arrSections=s.sections;sessionConfig=s.session;renderMixer();}
function disposeMixerBuses(){mixerNodes.forEach(n=>{try{n.disconnect();}catch(e){}});mixerNodes=[];mixerBuses={};}
function buildMixerBuses(a){disposeMixerBuses();if(!current)return;current.parts.forEach(p=>{const g=a.createGain();const m=mixer[p.id]||{volume:80,pan:0};g.gain.value=m.volume/100;mixerBuses[p.id]=g;mixerNodes.push(g);if(a.createStereoPanner){const pan=a.createStereoPanner();pan.pan.value=m.pan/100;g.connect(pan);pan.connect(master);mixerNodes.push(pan);g._pan=pan;}else g.connect(master);});}
function renderMixer(){if(!$('mixerPanel'))return;$('mixerPanel').innerHTML=PART_ORDER.filter(id=>document.querySelector('[data-part="'+id+'"]')?.checked).map(id=>{const m=mixer[id]||{volume:80,pan:0};return '<div class="channel" style="--track:'+PART_DEFS[id].colour+'"><strong>'+PART_DEFS[id].label+'</strong><label>Level <output id="level-'+id+'">'+m.volume+'%</output><input type="range" data-level="'+id+'" min="0" max="100" value="'+m.volume+'"></label><label>Pan <output id="pan-'+id+'">'+m.pan+'</output><input type="range" data-pan="'+id+'" min="-100" max="100" value="'+m.pan+'"></label><button data-open-sound="'+id+'" '+(['drums','kick'].includes(id)?'disabled title="Vaste percussiepreview"':'')+'>Sound</button></div>';}).join('');}
$('toggleMixer').onclick=()=>{$('mixerPanel').hidden=!$('mixerPanel').hidden;$('toggleMixer').setAttribute('aria-expanded',!$('mixerPanel').hidden);renderMixer();};
$('mixerPanel').addEventListener('input',e=>{const id=e.target.dataset.level||e.target.dataset.pan;if(!id)return;mixer[id]||={volume:80,pan:0};if(e.target.dataset.level){mixer[id].volume=+e.target.value;$('level-'+id).textContent=e.target.value+'%';if(mixerBuses[id])mixerBuses[id].gain.value=+e.target.value/100;}else{mixer[id].pan=+e.target.value;$('pan-'+id).textContent=e.target.value;if(mixerBuses[id]?._pan)mixerBuses[id]._pan.pan.value=+e.target.value/100;}});
$('mixerPanel').addEventListener('change',()=>{saveToHash();rememberTake();});
$('mixerPanel').addEventListener('click',e=>{const b=e.target.closest('[data-open-sound]');if(b){$('soundPart').value=b.dataset.openSound;selectView('sound');}});
$('clearMix').onclick=()=>{PART_ORDER.forEach(id=>{muted[id]=false;soloed[id]=false;});paintMS();rollCache=null;drawRoll();if(playing)playAll();};
function snapshot(){return {state:collectState(),clip:current?clone(current):null,source:baseLoop?clone(baseLoop):null,linked:vocalLinked};}
function rememberTake(){
  if(historyRestoring||!current)return;const snap=snapshot();const last=undoHistory[historyIndex];if(last&&JSON.stringify(last)===JSON.stringify(snap))return;
  undoHistory=undoHistory.slice(0,historyIndex+1);undoHistory.push(snap);if(undoHistory.length>16)undoHistory.shift();historyIndex=undoHistory.length-1;paintHistory();renderMixer();
}
function paintHistory(){$('undoTake').disabled=historyIndex<=0;$('redoTake').disabled=historyIndex>=undoHistory.length-1;$('historyHint').textContent=current?(current.arrangement?'ARRANGEMENT':'CLIP')+' · '+current.meta.bars+' maten':'';}
function restoreSnapshot(s){historyRestoring=true;stopAudio();location.hash=encodeURIComponent(JSON.stringify(s.state));restoreFromHash();current=clone(s.clip);baseLoop=clone(s.source);vocalLinked=!!s.linked&&!!vocalBuffer&&current?.vocalSourceSerial===vocalSourceSerial;redrawCurrent();historyRestoring=false;paintHistory();}
function redrawCurrent(){rollCache=null;refreshWorkspace();drawRoll();writeReadout();buildExports();updateStyleLabels();renderMixer();renderStudio();if(current)$('meta').textContent=NOTE_NAMES[current.meta.root]+' · '+current.bpm+' BPM · '+current.meta.bars+' maten'+(current.arrangement?' · Arrangement':'');saveToHash();}
$('undoTake').onclick=()=>{if(historyIndex>0)restoreSnapshot(undoHistory[--historyIndex]);};$('redoTake').onclick=()=>{if(historyIndex<undoHistory.length-1)restoreSnapshot(undoHistory[++historyIndex]);};
$('storeA').onclick=()=>{if(current){takeA=snapshot();$('recallA').disabled=false;$('historyHint').textContent='A bewaard — inclusief noten en soundinstellingen';}};
$('recallA').onclick=()=>{if(takeA){restoreSnapshot(takeA);rememberTake();}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){e.preventDefault();$(e.shiftKey?'redoTake':'undoTake').click();}});

function pageMarkup(id,title,body){const s=document.createElement('section');s.id='view-'+id;s.className='tool-view';s.hidden=true;s.setAttribute('role','tabpanel');s.setAttribute('aria-labelledby','tab-'+id);s.innerHTML='<div class="eyebrow">MIDIROOM / PRODUCE</div><h2>'+title+'</h2>'+body;document.querySelector('body > script').before(s);}
pageMarkup('sound','Bouw de klank rond je frase.',`<p class="intro">Speel je MIDI af en vorm de previewklank. Deze instellingen zijn geen VST-preset en zitten niet in de MIDI-export.</p><div class="sound-strip"><div class="field"><label for="soundPart">Instrument</label><select id="soundPart"></select></div><div class="field"><label for="soundPreset">Startpunt</label><select id="soundPreset"><option value="">Eigen instellingen</option></select></div><button id="soundPlay" class="primary">Speel sessie</button><button id="soundStop">Stop</button><button id="soundReset">Originele preview</button></div><div class="synth-panel"><div class="synth-top"><span class="eyebrow">DUAL OSC / LOWPASS / DRIVE</span><span id="patchStatus" class="pill">Preview synth</span></div><div class="knob-grid" id="soundControls"></div><div class="signal-path">OSC × 2 <span>→</span> LOWPASS <span>→</span> DRIVE <span>→</span> AMP <span>→</span> MIXER</div></div><div class="tool-grid" style="margin-top:20px"><article class="tool-card"><h3>Van schets naar synth</h3><p id="soundRecipe"></p><button id="exportPatch">Download klankrecept</button></article><article class="tool-card"><h3>Luister met een doel</h3><p>Solo het instrument in de generator. Begin met de envelope, daarna filter en drive. Luister vervolgens in de volledige sessie: een sterke soloklank kan te veel ruimte innemen naast je vocal.</p><p>Level en pan zijn preview-mixerinstellingen. Exporteer je recept om de klank in je DAW opnieuw op te bouwen.</p></article></div>`);
PART_ORDER.filter(id=>id!=='drums'&&id!=='kick').forEach(id=>{$('soundPart').add(new Option(PART_DEFS[id].label,id));});Object.keys(PATCHES).forEach(id=>$('soundPreset').add(new Option(id,id)));
const SOUND_PARAMS=[['cutoff','Cutoff',80,12000,10,'Hz'],['resonance','Resonance',.1,12,.1,'Q'],['attack','Attack',.003,1,.001,'s'],['release','Release',.02,1.5,.01,'s'],['drive','Drive',0,100,1,'%'],['detune','Detune',0,35,1,'ct']];
function renderSound(){const id=$('soundPart').value,p=soundPatches[id]||PATCHES['Warm pluck'];$('soundControls').innerHTML='<div class="field"><label for="oscWave">Oscillator</label><select id="oscWave">'+['sine','triangle','sawtooth','square'].map(w=>'<option '+(w===p.wave?'selected':'')+'>'+w+'</option>').join('')+'</select></div>'+SOUND_PARAMS.map(([key,label,min,max,step,unit])=>'<label class="dial-label">'+label+'<output id="sound-'+key+'">'+p[key]+' '+unit+'</output><input type="range" data-sound="'+key+'" min="'+min+'" max="'+max+'" step="'+step+'" value="'+p[key]+'"></label>').join('');$('patchStatus').textContent=soundPatches[id]?'Eigen patch actief':'Originele preview actief';renderRecipe();}
function renderRecipe(){const id=$('soundPart').value,p=soundPatches[id]||PATCHES['Warm pluck'];$('soundRecipe').textContent=PART_DEFS[id].label+': twee '+p.wave+' oscillatoren, ±'+p.detune+' cent. Low-pass '+p.cutoff+' Hz, Q '+p.resonance+'. Attack '+Math.round(p.attack*1000)+' ms, release '+Math.round(p.release*1000)+' ms. Drive '+p.drive+'%. Stem envelope en gain af op je eigen synth; de getallen zijn startpunten.';}
$('soundPart').onchange=renderSound;
$('soundPreset').onchange=()=>{if(PATCHES[$('soundPreset').value]){soundPatches[$('soundPart').value]=clone(PATCHES[$('soundPreset').value]);renderSound();saveToHash();rememberTake();if(playing)playAll();}};
$('soundControls').addEventListener('input',e=>{const id=$('soundPart').value,first=!soundPatches[id],p=soundPatches[id]||clone(PATCHES['Warm pluck']);if(e.target.dataset.sound){const key=e.target.dataset.sound;p[key]=+e.target.value;$('sound-'+key).textContent=p[key]+' '+SOUND_PARAMS.find(x=>x[0]===key)[5];}else if(e.target.id==='oscWave')p.wave=e.target.value;else return;soundPatches[id]=cleanPatch(p);$('patchStatus').textContent='Eigen patch actief';renderRecipe();if(first&&playing)playAll();});
$('soundControls').addEventListener('change',()=>{saveToHash();rememberTake();});
$('soundPlay').onclick=()=>{const id=$('soundPart').value;if(!current?.parts.some(p=>p.id===id)){$('patchStatus').textContent='Schakel dit instrument in bij MIDI Generator';return;}if(!soundPatches[id])soundPatches[id]=clone(PATCHES['Warm pluck']);playAll();};$('soundStop').onclick=stopAudio;
$('soundReset').onclick=()=>{delete soundPatches[$('soundPart').value];renderSound();saveToHash();rememberTake();if(playing)playAll();};
$('exportPatch').onclick=()=>downloadText('# MIDIROOM klankrecept\n\n'+$('soundRecipe').textContent+'\n\nDit is een recept, geen Serum/VST-preset.\n\n```json\n'+JSON.stringify(soundPatches[$('soundPart').value]||PATCHES['Warm pluck'],null,2)+'\n```','MIDIROOM_sound_recipe.md');
function patchVoice(a,out,t,freq,dur,vel,p){
  const filter=a.createBiquadFilter();filter.type='lowpass';filter.frequency.value=Math.min(p.cutoff,(a.sampleRate||44100)*.45);filter.Q.value=p.resonance;
  const gain=a.createGain(),end=t+dur+p.release,nodes=[filter,gain];const amp=.12*vel/127;gain.gain.setValueAtTime(.0001,t);gain.gain.linearRampToValueAtTime(amp,t+Math.min(p.attack,dur*.8));gain.gain.setValueAtTime(amp,t+dur);gain.gain.exponentialRampToValueAtTime(.0001,end);
  if(p.drive>0){const sh=a.createWaveShaper(),curve=new Float32Array(256),k=1+p.drive/8;for(let i=0;i<256;i++)curve[i]=Math.tanh((i/127.5-1)*k)/Math.tanh(k);sh.curve=curve;filter.connect(sh);sh.connect(gain);nodes.push(sh);}else filter.connect(gain);
  gain.connect(out);let ended=0;
  for(const sign of [-1,1]){const o=a.createOscillator();o.type=p.wave;o.frequency.value=freq;o.detune.value=sign*p.detune;o.connect(filter);
    o.onended=()=>{try{o.disconnect();}catch(e){}if(++ended===2)nodes.forEach(n=>{try{n.disconnect();}catch(e){}});};
    o.start(t);o.stop(end+.02);track(o,end+.05);
  }
}

pageMarkup('arrange','Geef je loop een verloop.',`<p class="intro">Bouw secties uit je huidige clip. Kies per sectie welke instrumenten spelen. De preview en MIDI-export nemen deze indeling over.</p><div class="action-row"><button id="arrUse">Gebruik huidige clip als bron</button><button id="arrTemplate">Intro → build → drop</button><button id="arrAdd">+ Sectie</button><button class="primary" id="arrBuild">Maak arrangement</button></div><div id="arrStatus" class="notice" role="status"></div><div class="arr-overview" id="arrOverview"></div><div id="arrRows" class="arr-rows"></div><p class="hint">Per sectie maximaal 32 maten; totaal maximaal 256. Dit rangschikt en herhaalt je bronloop. Nieuwe fills en audio-effecten worden niet automatisch toegevoegd.</p>`);
function defaultSections(){const parts=(baseLoop?.parts||current?.parts||[]).map(p=>p.id);return [{name:'Intro',bars:8,gain:.65,parts:parts.filter(id=>['drums','bass','pad','arp'].includes(id))},{name:'Build',bars:8,gain:.8,parts:parts.filter(id=>id!=='kick')},{name:'Drop',bars:16,gain:1,parts}];}
function renderArrangement(){if(!arrSections.length)arrSections=defaultSections();const source=baseLoop||current,parts=source?.parts||[];let bar=1;$('arrOverview').innerHTML=arrSections.map((s,i)=>{const st=bar;bar+=s.bars;return '<div class="arr-clip" style="flex:'+s.bars+'"><b>'+escapeHtml(s.name)+'</b><span>'+st+'–'+(bar-1)+'</span></div>';}).join('');$('arrRows').innerHTML=arrSections.map((s,i)=>'<article class="arr-row"><div class="arr-settings"><span class="eyebrow">'+String(i+1).padStart(2,'0')+'</span><input aria-label="Naam sectie '+(i+1)+'" data-arr="name" data-i="'+i+'" maxlength="30" value="'+escapeHtml(s.name)+'"><label>Maten <input type="number" data-arr="bars" data-i="'+i+'" min="1" max="32" value="'+s.bars+'"></label><label>Velocity <input type="range" data-arr="gain" data-i="'+i+'" min=".2" max="1.2" step=".05" value="'+s.gain+'"></label><button data-move="'+i+'" data-dir="-1" '+(i===0?'disabled':'')+' aria-label="Sectie omhoog">↑</button><button data-move="'+i+'" data-dir="1" '+(i===arrSections.length-1?'disabled':'')+' aria-label="Sectie omlaag">↓</button><button data-duplicate="'+i+'">Dupliceer</button><button data-remove="'+i+'" '+(arrSections.length===1?'disabled':'')+'>×</button></div><div class="arr-parts">'+parts.map(p=>'<button data-arr-part="'+p.id+'" data-i="'+i+'" aria-pressed="'+s.parts.includes(p.id)+'" style="--track:'+p.colour+'">'+p.label+'</button>').join('')+'</div></article>').join('');$('arrStatus').textContent=source?'Bron: '+source.meta.bars+' maten · '+(bar-1)+' maten totaal · '+((bar-1)*240/source.bpm).toFixed(1)+' s':'Genereer eerst een clip.';}
$('arrUse').onclick=()=>{if(current){baseLoop=clone(current);arrSections=defaultSections();renderArrangement();saveToHash();rememberTake();}};
$('arrTemplate').onclick=()=>{arrSections=defaultSections();renderArrangement();saveToHash();rememberTake();};
$('arrAdd').onclick=()=>{if(arrSections.length<16){arrSections.push({name:'Sectie',bars:8,gain:1,parts:(baseLoop?.parts||[]).map(p=>p.id)});renderArrangement();saveToHash();rememberTake();}};
$('arrRows').addEventListener('change',e=>{const i=+e.target.dataset.i,key=e.target.dataset.arr;if(!arrSections[i]||!key)return;arrSections[i][key]=key==='name'?e.target.value.slice(0,30):key==='bars'?Math.round(bound(e.target.value,1,32,8)):bound(e.target.value,.2,1.2,1);renderArrangement();saveToHash();rememberTake();});
$('arrRows').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.arrPart){const s=arrSections[+b.dataset.i],id=b.dataset.arrPart;s.parts=s.parts.includes(id)?s.parts.filter(x=>x!==id):[...s.parts,id];}else if(b.dataset.move!==undefined){const i=+b.dataset.move,j=i+(+b.dataset.dir);if(j>=0&&j<arrSections.length)[arrSections[i],arrSections[j]]=[arrSections[j],arrSections[i]];}else if(b.dataset.duplicate!==undefined&&arrSections.length<16)arrSections.splice(+b.dataset.duplicate+1,0,clone(arrSections[+b.dataset.duplicate]));else if(b.dataset.remove!==undefined&&arrSections.length>1)arrSections.splice(+b.dataset.remove,1);renderArrangement();saveToHash();rememberTake();});
function arrangeClip(source,sections){const total=sections.reduce((n,s)=>n+s.bars,0);if(!source||!source.parts.length)throw new Error('Genereer eerst een bronclip.');if(total>256)throw new Error('Maximaal 256 maten per arrangement.');const length=source.meta.bars*1920;let cursor=0;const marks=[];const tracks=source.parts.map(p=>({...clone(p),events:[],part:{bars:[]}}));sections.forEach(s=>{marks.push({bar:cursor,label:s.name,bars:s.bars});const end=s.bars*1920;tracks.forEach(p=>{if(!s.parts.includes(p.id))return;const original=source.parts.find(x=>x.id===p.id);for(let rep=0;rep<end;rep+=length)original.events.forEach(e=>{const at=rep+e.tick;if(at<end)p.events.push({...e,tick:cursor*1920+at,dur:Math.min(e.dur,end-at),vel:Math.max(1,Math.min(127,Math.round(e.vel*s.gain)))});});});cursor+=s.bars;});return {...clone(source),parts:tracks.filter(p=>p.events.length),arrangement:true,meta:{...clone(source.meta),bars:total,marks,structure:{id:'custom',label:'Eigen arrangement'}}};}
$('arrBuild').onclick=()=>{try{const clip=arrangeClip(baseLoop||current,arrSections);if(!clip.parts.length)throw new Error('Schakel in minstens één sectie een instrument in.');stopAudio();current=clip;vocalLinked=false;redrawCurrent();rememberTake();selectView('generator');}catch(e){$('arrStatus').textContent=e.message;}};

pageMarkup('vocal','Maak ruimte voor de stem.',`<p class="intro">Laad een droge, solo vocal. De analyse schat majeur/mineur en gezongen nootaanzetten. Controleer de key en luister samen voordat je exporteert.</p><label class="upload-zone">+ Kies vocal (WAV / MP3 / ondersteund audioformaat)<input type="file" id="vocalFile" accept="audio/*"></label><p class="hint" id="vocalName" style="margin-top:12px"></p><div class="notice" id="vocalStatus" role="status">Lokaal verwerkt. Maximaal 20 MB en 90 seconden; kies bij voorkeur een korte, schone frase.</div><canvas id="vocalWave" height="120" aria-label="Golfvorm van de vocal"></canvas><audio id="vocalAudio" controls></audio><div class="sound-strip"><button id="analyseVocal" class="primary" disabled>Analyseer vocal</button><button id="cancelVocal" disabled>Annuleer analyse</button><button id="removeVocal" disabled>Verwijder vocal</button></div><div id="keyCandidates" class="key-candidates"></div><div class="tool-grid"><article class="tool-card"><h3>Key &amp; timing</h3><div class="row"><div class="field"><label for="vocalRoot">Grondtoon</label><select id="vocalRoot"></select></div><div class="field"><label for="vocalScale">Toonladder</label><select id="vocalScale"><option value="aeolian">Mineur</option><option value="ionian">Majeur</option></select></div></div><div class="row"><div class="field"><label for="vocalBpm">Project BPM</label><input type="number" id="vocalBpm" min="40" max="300" value="130"></div><div class="field"><label for="vocalOffset">Vocal start na (seconden)</label><input type="number" id="vocalOffset" min="0" max="30" step=".01" value="0"></div></div><p>BPM komt uit jouw project; de app raadt geen stabiel tempo uit een vrije zangpartij. De gedetecteerde timing blijft in seconden behouden, ook bij rubato.</p></article><article class="tool-card"><h3>Begeleiding</h3><div class="field"><label for="vocalMode">Ritme van de melodie</label><select id="vocalMode"><option value="follow">Volg gedetecteerde nootaanzetten</option><option value="space">Meer ruimte — om en om</option></select></div><p>Een lagere tegenstem volgt de toonladder en het geschatte zangritme. Akkoorden zijn een startpunt in dezelfde key, geen automatische harmonische transcriptie.</p><div class="action-row"><button class="primary" id="vocalGenerate" disabled>Maak begeleiding</button><button id="vocalTogether" disabled>Vocal + MIDI</button><button id="vocalStop">Stop alles</button></div><label class="check" style="margin-top:14px">Vocal level <input type="range" id="vocalLevel" min="0" max="100" value="65"></label></article></div><p class="hint" style="margin-top:20px">De vocal blijft alleen in deze sessie. Idea Bank bewaart MIDI en instellingen, niet het audiobestand. De analyse kan consonanten, effecten en adem verwarren met nootaanzetten; dit is geen woord-/lettergreeptranscriptie.</p>`);
NOTE_NAMES.forEach((n,i)=>$('vocalRoot').add(new Option(n,i)));
function clearVocal(){vocalLoadId++;if(vocalWorker)vocalWorker.terminate();vocalWorker=null;vocalBuffer=null;vocalAnalysis=null;vocalLinked=false;stopAudio();$('vocalAudio').pause();$('vocalAudio').removeAttribute('src');if(vocalURL)URL.revokeObjectURL(vocalURL);vocalURL=null;$('vocalFile').value='';$('vocalName').textContent='';$('keyCandidates').innerHTML='';['analyseVocal','vocalGenerate','vocalTogether','removeVocal','cancelVocal'].forEach(id=>$(id).disabled=true);const c=$('vocalWave');c.getContext('2d').clearRect(0,0,c.width,c.height);}
$('removeVocal').onclick=()=>{clearVocal();$('vocalStatus').textContent='Vocal verwijderd.';};
$('vocalFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;clearVocal();const token=vocalLoadId;try{if(file.size>20*1024*1024)throw new Error('Maximaal 20 MB.');$('vocalStatus').textContent='Vocal laden…';const context=ac();if(!context)throw new Error('Deze browser ondersteunt geen audioanalyse.');const buffer=await context.decodeAudioData(await file.arrayBuffer());if(token!==vocalLoadId)return;if(buffer.duration>90)throw new Error('Maximaal 90 seconden. Knip eerst een korte frase.');vocalBuffer=buffer;$('vocalName').textContent='Geladen: '+file.name;vocalURL=URL.createObjectURL(file);$('vocalAudio').src=vocalURL;$('vocalStatus').textContent=file.name+' · '+buffer.duration.toFixed(1)+' s · klaar voor analyse';$('analyseVocal').disabled=false;$('removeVocal').disabled=false;drawVocalWave();if(typeof renderSession==='function')renderSession();}catch(err){if(token===vocalLoadId)$('vocalStatus').textContent='Laden mislukt: '+err.message;}};
function drawVocalWave(){if(!vocalBuffer)return;const c=$('vocalWave');c.width=Math.max(300,c.clientWidth);const g=c.getContext('2d'),data=vocalBuffer.getChannelData(0);g.clearRect(0,0,c.width,c.height);g.strokeStyle='#91cfe9';g.beginPath();for(let x=0;x<c.width;x++){let amp=0;const step=Math.max(1,Math.floor(data.length/c.width));for(let i=x*step;i<Math.min(data.length,(x+1)*step);i+=Math.max(1,Math.floor(step/30)))amp=Math.max(amp,Math.abs(data[i]));g.moveTo(x,60-amp*55);g.lineTo(x,60+amp*55);}g.stroke();}
$('analyseVocal').onclick=async()=>{if(!vocalBuffer)return;const token=vocalLoadId;try{$('analyseVocal').disabled=true;$('cancelVocal').disabled=false;$('vocalStatus').textContent='Pitch en aanzetten analyseren…';const off=new OfflineAudioContext(1,Math.ceil(vocalBuffer.duration*8000),8000),src=off.createBufferSource();src.buffer=vocalBuffer;src.connect(off.destination);src.start();const resampled=await off.startRendering();if(token!==vocalLoadId)return;const data=resampled.getChannelData(0).slice();const code='const analyseVocal='+analyseVocal.toString()+';onmessage=e=>{try{postMessage({result:analyseVocal(e.data)})}catch(error){postMessage({error:error.message})}}';const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));vocalWorker=new Worker(url);URL.revokeObjectURL(url);vocalWorker.onmessage=e=>{if(token!==vocalLoadId)return;vocalWorker.terminate();vocalWorker=null;$('analyseVocal').disabled=false;$('cancelVocal').disabled=true;if(e.data.error){$('vocalStatus').textContent=e.data.error;return;}vocalAnalysis=e.data.result;showVocalAnalysis();};vocalWorker.onerror=()=>{$('vocalStatus').textContent='Analyse niet beschikbaar in deze browser.';$('analyseVocal').disabled=false;$('cancelVocal').disabled=true;if(vocalWorker)vocalWorker.terminate();vocalWorker=null;};vocalWorker.postMessage(data,[data.buffer]);}catch(err){$('vocalStatus').textContent='Analyse mislukt: '+err.message;$('analyseVocal').disabled=false;$('cancelVocal').disabled=true;}};
$('cancelVocal').onclick=()=>{vocalLoadId++;if(vocalWorker)vocalWorker.terminate();vocalWorker=null;$('analyseVocal').disabled=!vocalBuffer;$('cancelVocal').disabled=true;$('vocalStatus').textContent='Analyse geannuleerd.';};
function showVocalAnalysis(){const a=vocalAnalysis;if(!a.segments.length||!a.keys.length){$('vocalStatus').textContent='Geen betrouwbare zangnoten gevonden. Probeer een droge solo vocal.';$('vocalGenerate').disabled=true;return;}$('vocalRoot').value=a.keys[0].root;$('vocalScale').value=a.keys[0].scale;$('keyCandidates').innerHTML=a.keys.map((k,i)=>'<button data-key-candidate="'+i+'">'+NOTE_NAMES[k.root]+' '+(k.scale==='ionian'?'majeur':'mineur')+(i===0?' · eerste schatting':'')+'</button>').join('');$('vocalStatus').textContent=a.segments.length+' nootaanzetten · '+a.voicedSeconds.toFixed(1)+' s zang · zekerheid: '+a.certainty+'. Controleer ook de alternatieven.';$('vocalGenerate').disabled=false;}
$('keyCandidates').onclick=e=>{const b=e.target.closest('[data-key-candidate]');if(b){const k=vocalAnalysis.keys[+b.dataset.keyCandidate];$('vocalRoot').value=k.root;$('vocalScale').value=k.scale;}};
$('vocalGenerate').onclick=()=>{if(!vocalAnalysis?.segments.length)return;const bpm=Math.round(bound($('vocalBpm').value,40,300,130)),offset=bound($('vocalOffset').value,0,30,0),root=+$('vocalRoot').value,sc=$('vocalScale').value;const bars=Math.ceil((vocalBuffer.duration+offset)*bpm/240);if(bars>128){$('vocalStatus').textContent='Deze vocal is te lang bij dit tempo (max. 128 maten).';return;}
  $('bpm').value=bpm;$('root').value=root;$('scale').value=sc;$('structure').value='';$('bars').disabled=false;$('prog').value='pedal';activeGenre='free';document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('on',b.dataset.genre==='free'));$('genreNote').textContent='Vocalbegeleiding · geschatte key en nootaanzetten';
  const parts=['bass','pad','melody'];document.querySelectorAll('[data-part]').forEach(cb=>{cb.checked=parts.includes(cb.dataset.part);cb.closest('.part').classList.toggle('active',cb.checked);});
  const clip=generateSection({seed:$('seed').value,root,octave:5,scale:sc,progression:'pedal',bars,bpm,chordSize:3,chordBars:4,parts:['bass','pad'],partOpts:{bass:{style:'heel'},pad:{style:'whole'}},tries:8});
  const events=vocalMelodyEvents(vocalAnalysis.segments,root,SCALES[sc].steps,bpm,offset,$('vocalMode').value);clip.parts.push({id:'melody',label:'Melody',colour:PART_DEFS.melody.colour,events,part:{bars:[],rhythmLabel:'Vocal timing'}});clip.bpm=bpm;stopAudio();current=clip;vocalLinked=true;current.vocalOffset=offset;current.vocalTiming=true;baseLoop=clone(current);redrawCurrent();rememberTake();$('vocalTogether').disabled=false;$('vocalStatus').textContent='Begeleiding klaar: '+bars+' maten. Luister samen en controleer de key.';
};
let vocalGain=null;
function scheduleLinkedVocal(a,start){if(!vocalLinked||!vocalBuffer||current?.vocalSourceSerial!==vocalSourceSerial)return;const source=a.createBufferSource();source.buffer=vocalBuffer;vocalGain=a.createGain();vocalGain.gain.value=+$('vocalLevel').value/100*.55;const ownGain=vocalGain;source.connect(ownGain);ownGain.connect(master||a.destination);source.start(start+(current.vocalOffset||0));source.stop(start+sectionDur);source.onended=()=>{try{source.disconnect();ownGain.disconnect();}catch(e){}};track(source,start+sectionDur+.1);}
$('vocalTogether').onclick=()=>{if(vocalLinked){$('vocalAudio').pause();$('loop').checked=false;playAll();}};
$('vocalStop').onclick=()=>{stopAudio();$('vocalAudio').pause();};$('vocalLevel').oninput=()=>{if(vocalGain)vocalGain.gain.value=+$('vocalLevel').value/100*.55;};
restoreStudioState({});renderSound();
// Persist exact note snapshots for custom arrangements and vocal-derived clips.
function cleanClip(c){
  if(!c)return null;
  if(!c.meta||!Array.isArray(c.parts)||c.parts.length>12)throw new Error('Ongeldige clip.');
  const bars=Math.round(bound(c.meta.bars,1,256,8)),bpm=Math.round(bound(c.bpm||c.meta.bpm,40,300,130));let count=0;const ids=new Set();
  const parts=c.parts.map(p=>{if(!PART_DEFS[p.id]||ids.has(p.id)||!Array.isArray(p.events))throw new Error('Ongeldige clip-partij.');ids.add(p.id);count+=p.events.length;if(count>50000)throw new Error('Clip bevat te veel noten.');
    const events=p.events.map(e=>{if(![e.tick,e.dur,e.midi,e.vel].every(Number.isInteger)||e.tick<0||e.dur<=0||e.tick+e.dur>bars*1920||e.midi<0||e.midi>127||e.vel<1||e.vel>127)throw new Error('Ongeldige MIDI-noot.');return {tick:e.tick,dur:e.dur,midi:e.midi,vel:e.vel};}).sort((a,b)=>a.tick-b.tick||a.midi-b.midi);
    return {id:p.id,label:PART_DEFS[p.id].label,colour:PART_DEFS[p.id].colour,events,part:{bars:[],rhythmLabel:c.vocalTiming?'Vocal timing':'Bewaarde take'}};});
  const progression=PROGRESSIONS.find(p=>p.id===c.meta.progression?.id)||PROGRESSIONS[0];
  const marks=Array.isArray(c.meta.marks)?c.meta.marks.slice(0,16).map(m=>({bar:Math.round(bound(m.bar,0,bars-1,0)),bars:Math.round(bound(m.bars,1,32,8)),label:String(m.label||'Sectie').slice(0,30)})):null;
  return {parts,bpm,arrangement:!!c.arrangement,customEdit:!!c.customEdit,vocalMode:['follow','answer','support'].includes(c.vocalMode)?c.vocalMode:undefined,vocalTiming:!!c.vocalTiming,vocalOffset:bound(c.vocalOffset,0,30,0),meta:{bars,bpm,progression,root:Math.round(bound(c.meta.root,0,11,0)),seed:String(c.meta.seed||'').slice(0,120),scale:Object.values(SCALES).find(s=>JSON.stringify(s.steps)===JSON.stringify(c.meta.scale?.steps))||SCALES.aeolian,...(marks?{marks}:{}),...(c.arrangement?{structure:{id:'custom',label:'Bewaard arrangement'}}:{})}};
}

function refreshProduction(){
  const special=!!(current?.vocalTiming||current?.customEdit||current?.meta.structure?.id==='custom');
  $('clipNotice').hidden=!special;$('clipNotice').textContent='Bewerkte clip actief. Nieuwe generatie vervangt deze noten; bewaar de take om exact terug te kunnen.';
  $('bars').disabled=special||!!$('structure').value;
  $('vocalTogether').disabled=!vocalLinked||!vocalBuffer||!current?.vocalTiming;
  if(typeof renderSession==='function')renderSession();
  $('storeA').disabled=!current;$('soundPlay').disabled=!current;$('arrBuild').disabled=!baseLoop&&!current;
}
