/* 2.3 session UI and explicit composition actions. */
const ICONS={lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4"/>',unlock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 7-2"/>',vary:'<path d="M3 6h3c5 0 7 12 12 12h3M18 15l3 3-3 3M3 18h3c2 0 4-3 6-6s4-6 6-6h3M18 3l3 3-3 3"/>',sliders:'<path d="M5 3v18M12 3v18M19 3v18M2 8h6M9 16h6M16 7h6"/>',mic:'<rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',download:'<path d="M12 3v12M7 10l5 5 5-5M4 16v5h16v-5"/>',music:'<path d="M9 18V5l11-2v13M9 9l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/>'};
function icon(name){return '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(ICONS[name]||ICONS.music)+'</svg>';}
var selectedInstrument='bass',sessionReady=false;
const inspector=document.createElement('section');inspector.id='inspector';inspector.innerHTML='<div class="inspector-head"><span class="eyebrow">TRACK INSPECTOR</span><button id="closeInspector" aria-label="Instellingen sluiten">×</button></div><h2 id="inspectorTitle"></h2><p id="inspectorInfo" class="hint"></p><div class="inspector-actions"><button id="inspectorVary">'+icon('vary')+' Varieer</button><button id="inspectorLock">'+icon('lock')+' Lock</button><button id="inspectorExport" title="Download deze track">'+icon('download')+' MIDI</button></div><div id="inspectorBody"></div><p class="hint">Lock bewaart deze noten exact. M en S bepalen alleen wat je hoort.</p>';document.querySelector('.wrap').appendChild(inspector);
PART_ORDER.forEach(id=>{
 const row=document.querySelector('.part[data-id="'+id+'"]');row.style.setProperty('--track',PART_DEFS[id].colour);
 const name=row.querySelector('.nm'),button=document.createElement('button');button.className='track-name';button.textContent=PART_DEFS[id].label;button.dataset.selectTrack=id;name.replaceWith(button);
 const edit=row.querySelector('[data-edit]');edit.innerHTML=icon('sliders');edit.title='Instellingen';
 const v=row.querySelector('[data-vary]');v.innerHTML=icon('vary');v.title='Nieuwe noten, ritme en lengtes';
 const lock=document.createElement('button');lock.dataset.lock=id;lock.className='track-lock';lock.innerHTML=icon('unlock');lock.title='Track vastzetten';lock.setAttribute('aria-label',PART_DEFS[id].label+' vastzetten');lock.setAttribute('aria-pressed','false');edit.before(lock);
 const body=row.querySelector('.part-body');body.hidden=true;$('inspectorBody').appendChild(body);
});
inspector.addEventListener('change',handlePartChange);inspector.addEventListener('click',e=>{if(e.target.closest('[data-oct]'))handlePartClick(e);});
function selectInstrument(id){if(!PART_DEFS[id])return;selectedInstrument=id;document.body.classList.remove('inspector-closed');PART_ORDER.forEach(pid=>{const row=document.querySelector('.part[data-id="'+pid+'"]');row.classList.toggle('selected',pid===id);$('settings-'+pid).hidden=pid!==id;row.querySelector('[data-edit]').setAttribute('aria-expanded',pid===id);});$('inspectorTitle').textContent=PART_DEFS[id].label;inspector.style.setProperty('--track',PART_DEFS[id].colour);renderSession();}
$('closeInspector').onclick=()=>document.body.classList.add('inspector-closed');
$('inspectorVary').onclick=()=>varySession(selectedInstrument);$('inspectorLock').onclick=()=>toggleTrackLock(selectedInstrument);$('inspectorExport').onclick=()=>{const p=current?.parts.find(p=>p.id===selectedInstrument);if(p)download(buildMidi([{id:p.id,name:p.label,events:p.events}],current.bpm,current.meta.bars*1920),fileStem()+'_'+p.id+'.mid');};
$('parts').addEventListener('click',e=>{const b=e.target.closest('[data-lock]');if(b){e.stopPropagation();toggleTrackLock(b.dataset.lock);}const s=e.target.closest('[data-select-track]');if(s)selectInstrument(s.dataset.selectTrack);},true);
const genreField=document.createElement('div');genreField.className='field genre-field';genreField.innerHTML='<label for="genreSelect">Genre</label><select id="genreSelect">'+GENRES.map(g=>'<option value="'+g.id+'">'+g.label+'</option>').join('')+'</select>';document.querySelector('.session-controls').prepend(genreField);$('genreSelect').onchange=()=>{if(current){current.vocalTiming=false;delete current.vocalSourceSerial;}const custom=$('bars').querySelector('[data-custom-length]');if(custom){$('bars').value='8';custom.remove();}vocalLinked=false;applyGenre($('genreSelect').value,true);};
const composition=document.createElement('div');composition.className='composition-strip';composition.innerHTML='<label>Variatie <select id="variationStrength"><option value="subtle">Subtiel</option><option value="explore" selected>Ontdekken</option><option value="wild">Avontuurlijk</option></select></label><label>Samenspel <select id="relationMode"><option value="off">Vrij</option><option value="harmonic">Harmonisch</option><option value="space" selected>Ruimte maken</option></select></label><button id="unlockAll">'+icon('unlock')+' Ontgrendel</button><span id="sessionNotice" role="status"></span>';document.querySelector('.session-controls').after(composition);
['variationStrength','relationMode'].forEach(id=>$(id).onchange=()=>{sessionConfig[id==='variationStrength'?'strength':'relation']=$(id).value;saveToHash();rememberTake();});
$('unlockAll').onclick=()=>{sessionConfig.locks={};renderSession();saveToHash();rememberTake();};
$('reroll').innerHTML=icon('vary')+' Ontdek variatie';$('gen').textContent='Genereer';
$('reroll').addEventListener('click',e=>{e.stopImmediatePropagation();varySession();},true);
// The vocal is a source track inside the generator; analysis lives in its drawer.
const vocalTrack=document.createElement('div');vocalTrack.className='vocal-track';vocalTrack.innerHTML='<div class="vocal-track-title">'+icon('mic')+'<strong>Vocal</strong><span id="vocalTrackBadge">Geen audio</span></div><div id="vocalTrackAction"></div><label class="check"><input type="checkbox" id="vocalAudible"> Hoorbaar bij Play</label><p id="vocalTrackInfo" class="hint"></p>';
document.querySelector('.track-search').after(vocalTrack);$('vocalTrackAction').appendChild($('tab-vocal'));$('tab-vocal').textContent='Vocal openen';$('tab-vocal').removeAttribute('role');$('tab-vocal').removeAttribute('aria-selected');$('tab-vocal').tabIndex=0;
const drawer=document.createElement('details');drawer.id='vocalDrawer';drawer.innerHTML='<summary>'+icon('mic')+' Vocal · bron & begeleiding <span id="vocalSummary">Voeg een vocal toe</span></summary><div id="vocalContent"></div>';document.querySelector('.rollbox').before(drawer);
while($('view-vocal').firstChild)$('vocalContent').appendChild($('view-vocal').firstChild);
$('vocalContent').querySelector('h2').textContent='Van zang naar begeleiding';$('vocalContent').querySelector('.eyebrow')?.remove();
$('vocalContent').querySelector('.intro').textContent='1. Laad en analyseer → 2. Controleer de zangnoten → 3. Maak MIDI. De vocal is daarna onderdeel van deze sessie.';
$('vocalMode').innerHTML='<option value="follow">Volgen · zingritme en contour</option><option value="answer">Antwoorden · in de zangpauzes</option><option value="support">Ondersteunen · rustige harmonie</option>';
$('vocalGenerate').textContent='Maak MIDI uit vocal';$('vocalTogether').textContent='Speel vocal + MIDI';$('vocalStop').textContent='Stop';
const linkButton=document.createElement('button');linkButton.id='linkVocalReference';linkButton.textContent='Koppel audio aan huidige MIDI';$('vocalTogether').after(linkButton);
const freeButton=document.createElement('button');freeButton.id='freeVocalMidi';freeButton.textContent='Verder als vrije MIDI';$('linkVocalReference').after(freeButton);freeButton.onclick=()=>{if(current){current.vocalTiming=false;current.customEdit=true;renderSession();rememberTake();sessionMessage('Vrije MIDI: vocal blijft alleen een audioreferentie.');}};
const correction=document.createElement('details');correction.id='vocalCorrections';correction.innerHTML='<summary>Controleer & corrigeer zangnoten <span id="vocalNoteCount"></span></summary><canvas id="vocalNotesLane" height="120" aria-label="Gedetecteerde zangnoten"></canvas><p class="hint">Tijden zijn seconden in de originele opname. Corrigeer pitch of timing, of verwijder een foutieve noot. Maak daarna de begeleiding opnieuw.</p><div id="vocalNotesEditor"></div><button id="vocalAddNote">+ Zangnoot</button>'; $('vocalWave').after(correction);
const lane=document.createElement('div');lane.id='vocalSessionLane';lane.innerHTML='<div><span>'+icon('mic')+' Vocalreferentie</span><span id="vocalLaneLabel"></span></div><canvas id="vocalAligned" height="76" aria-label="Vocalnoten uitgelijnd op de MIDI tijdlijn"></canvas>';$('rollViewport').prepend(lane);
$('rollZoom').addEventListener('change',()=>{lane.style.width=(+$('rollZoom').value*100)+'%';drawVocalNotes();});
const oldShowVocal=showVocalAnalysis;showVocalAnalysis=function(){vocalRevision++;oldShowVocal();renderVocalEditor();renderSession();};
const oldClearVocal=clearVocal;clearVocal=function(){oldClearVocal();$('vocalAudio').load();$('vocalCorrections').open=false;vocalSourceSerial++;renderVocalEditor();renderSession();};
let vocalSourceSerial=0,vocalRevision=0;
$('vocalFile').addEventListener('change',()=>setTimeout(renderSession,100));
$('vocalAudible').onchange=()=>{vocalLinked=$('vocalAudible').checked&&!!vocalBuffer&&current?.vocalSourceSerial===vocalSourceSerial;const was=playing;if(was)playAll();renderSession();};
$('linkVocalReference').onclick=()=>{if(!vocalBuffer||!current)return;current.vocalTiming=false;current.vocalSourceSerial=vocalSourceSerial;current.vocalOffset=bound($('vocalOffset').value,0,30,0);vocalLinked=true;$('loop').checked=false;renderSession();rememberTake();};
$('vocalTogether').onclick=()=>{if(!current||!vocalBuffer||current.vocalSourceSerial!==vocalSourceSerial)return;vocalLinked=true;$('vocalAudio').pause();$('loop').checked=false;playAll();renderSession();};
$('vocalGenerate').onclick=()=>makeVocalSession();
$('vocalNotesEditor').addEventListener('change',e=>{const i=+e.target.dataset.noteIndex,key=e.target.dataset.noteKey;if(!vocalAnalysis?.segments[i]||!key)return;const old=clone(vocalAnalysis.segments[i]);vocalAnalysis.segments[i][key]=Number(e.target.value);const s=vocalAnalysis.segments[i];if(!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end>safelyVocalDuration()||s.end<=s.start||!Number.isInteger(s.midi)||s.midi<24||s.midi>96){vocalAnalysis.segments[i]=old;$('vocalStatus').textContent='Ongeldige noot: controleer begin/einde en MIDI-pitch (24–96).';}else{vocalAnalysis.segments.sort((a,b)=>a.start-b.start);vocalRevision++;$('vocalStatus').textContent='Zangnoot aangepast. Maak de MIDI opnieuw om dit te horen.';}renderVocalEditor();renderSession();});
$('vocalNotesEditor').onclick=e=>{const b=e.target.closest('[data-remove-note]');if(b){vocalAnalysis.segments.splice(+b.dataset.removeNote,1);vocalRevision++;renderVocalEditor();renderSession();}};
$('vocalAddNote').onclick=()=>{if(!vocalAnalysis||vocalAnalysis.segments.length>=600)return;const start=Math.max(0,Math.min(safelyVocalDuration()-.1,(vocalAnalysis.segments.at(-1)?.end||0)));vocalAnalysis.segments.push({start,end:Math.min(safelyVocalDuration(),start+.2),midi:60,quality:1});vocalRevision++;renderVocalEditor();};
function safelyVocalDuration(){return vocalBuffer?.duration||vocalAnalysis?.duration||0;}
function renderVocalEditor(){const seg=vocalAnalysis?.segments||[];$('vocalNoteCount').textContent=seg.length?' · '+seg.length+' noten':'';$('vocalNotesEditor').innerHTML=seg.slice(0,600).map((s,i)=>'<div class="vocal-note-row"><span>'+String(i+1).padStart(2,'0')+'</span><label>Begin <input type="number" step=".01" min="0" data-note-index="'+i+'" data-note-key="start" value="'+s.start.toFixed(3)+'"></label><label>Einde <input type="number" step=".01" min="0" data-note-index="'+i+'" data-note-key="end" value="'+s.end.toFixed(3)+'"></label><label>Pitch <input type="number" min="24" max="96" step="1" data-note-index="'+i+'" data-note-key="midi" value="'+s.midi+'"></label><span>'+midiName(s.midi)+'</span><button data-remove-note="'+i+'" aria-label="Zangnoot '+(i+1)+' verwijderen">×</button></div>').join('')||'<p class="hint">Nog geen zangnoten. Analyseer eerst je vocal.</p>';$('vocalAddNote').disabled=!vocalAnalysis;drawVocalNotes();}
function drawVocalNotes(){if(!$('vocalAligned'))return;const segments=vocalAnalysis?.segments||[];for(const id of ['vocalNotesLane','vocalAligned']){const c=$(id),g=c.getContext('2d'),w=c.clientWidth||600;c.width=w;c.height=id==='vocalAligned'?76:120;g.clearRect(0,0,w,c.height);if(!segments.length)continue;const aligned=id==='vocalAligned',offset=aligned?(current?.vocalOffset||0):0,duration=aligned&&current?current.meta.bars*240/current.bpm:safelyVocalDuration();const lo=Math.min(...segments.map(s=>s.midi))-1,hi=Math.max(...segments.map(s=>s.midi))+1;g.fillStyle='#80d7c3';segments.forEach(s=>{const left=aligned?48:8,width=w-left;g.fillRect(left+(s.start+offset)/duration*width,8+(hi-s.midi)/(hi-lo)*(c.height-20),Math.max(2,(s.end-s.start)/duration*width),4);});}}
$('vocalCorrections').addEventListener('toggle',drawVocalNotes);drawer.addEventListener('toggle',()=>{drawVocalWave();drawVocalNotes();});
function cleanSessionConfig(s={}){return {performance:['off','natural','pocket','bold'].includes(s?.performance)?s.performance:'natural',strength:['subtle','explore','wild'].includes(s?.strength)?s.strength:'explore',relation:['off','harmonic','space'].includes(s?.relation)?s.relation:'space',locks:Object.fromEntries(PART_ORDER.filter(id=>s?.locks?.[id]).map(id=>[id,true]))};}
function toggleTrackLock(id){if(!current?.parts.some(p=>p.id===id))return;sessionConfig.locks[id]=!sessionConfig.locks[id];renderSession();saveToHash();rememberTake();}
function sessionMessage(text){if($('sessionNotice'))$('sessionNotice').textContent=text;}
function renderSession(){if(!sessionReady)return;
 const locks=sessionConfig.locks,hasLocks=Object.values(locks).some(Boolean),p=current?.parts.find(p=>p.id===selectedInstrument);
 PART_ORDER.forEach(id=>{const b=document.querySelector('[data-lock="'+id+'"]');b.setAttribute('aria-pressed',!!locks[id]);b.innerHTML=icon(locks[id]?'lock':'unlock');b.title=locks[id]?'Ontgrendel track':'Bewaar deze noten exact';document.querySelector('[data-vary="'+id+'"]').disabled=!!locks[id]||!current?.parts.some(p=>p.id===id);});
 $('variationStrength').value=sessionConfig.strength;$('relationMode').value=sessionConfig.relation;$('genreSelect').value=activeGenre;$('unlockAll').disabled=!hasLocks;
 ['root','scale','prog','bars','chordBars','chordSize','structure','genreSelect','energy'].forEach(id=>{$(id).disabled=hasLocks||(id==='bars'&&(!!current?.vocalTiming||!!$('structure').value||!!current?.arrangement));$(id).title=hasLocks?'Ontgrendel tracks om de harmonische context of lengte te veranderen':'';});
 const vocalControlled=!!current?.vocalTiming&&!!vocalAnalysis&&current?.vocalSourceSerial===vocalSourceSerial&&!['drums','kick'].includes(selectedInstrument);
 document.querySelectorAll('#inspectorBody input,#inspectorBody select,#inspectorBody button').forEach(c=>{c.disabled=!!locks[selectedInstrument]||vocalControlled;});
 $('inspectorInfo').textContent=p?p.events.length+' noten · '+(locks[selectedInstrument]?'vastgezet':vocalControlled?'vocalgestuurd · stijl wijzigen via Vrije MIDI':'vrij te variëren'):'Schakel deze track in om hem te horen.';
 $('inspectorVary').disabled=!p||!!locks[selectedInstrument];$('inspectorLock').disabled=!p;$('inspectorLock').setAttribute('aria-pressed',!!locks[selectedInstrument]);$('inspectorLock').innerHTML=icon(locks[selectedInstrument]?'lock':'unlock')+(locks[selectedInstrument]?' Vast':' Lock');$('inspectorExport').disabled=!p;
 if(current&&(current.vocalTiming||current.arrangement||current.customEdit)){let op=$('bars').querySelector('[data-custom-length]');if(![...$('bars').options].some(o=>+o.value===current.meta.bars)){if(!op){op=new Option();op.dataset.customLength='true';$('bars').add(op);}op.value=current.meta.bars;op.textContent=current.meta.bars;} $('bars').value=String(current.meta.bars);}
 const connected=!!vocalBuffer&&current?.vocalSourceSerial===vocalSourceSerial,guided=connected&&current?.vocalTiming;
 $('vocalWave').hidden=!vocalBuffer;$('vocalCorrections').hidden=!vocalAnalysis;$('vocalContent').querySelector('.tool-grid').hidden=!vocalAnalysis;document.querySelectorAll('.vocal-audio-options,.vocal-link-options').forEach(el=>el.hidden=!vocalBuffer);
 $('vocalAudible').disabled=!connected;$('vocalAudible').checked=connected&&vocalLinked;$('vocalTogether').disabled=!connected;$('linkVocalReference').disabled=!vocalBuffer||!current;
 $('freeVocalMidi').disabled=!guided;
 $('vocalTrackBadge').textContent=guided?'MIDI-bron':vocalBuffer?'Referentie':'Geen audio';$('vocalTrackInfo').textContent=guided?(vocalLinked?'Vocal + MIDI bij Play':'Alleen MIDI bij Play'):(connected?'Audio gekoppeld; MIDI niet uit vocal gemaakt.':'Open de vocal om audio te laden of te koppelen.');
 $('vocalSummary').textContent=guided?'Vocalbasis · '+({follow:'volgen',answer:'antwoorden',support:'ondersteunen'}[current.vocalMode]||'bewaarde MIDI'):vocalBuffer?'Geladen · maak of koppel MIDI':'Voeg een vocal toe';
 $('vocalSessionLane').hidden=!connected||!vocalAnalysis;$('vocalLaneLabel').textContent=guided?(current.customEdit?'Vocalbasis · vrije ritmevariatie':'Bron voor deze MIDI')+(current.vocalRevision!==vocalRevision?' · wijzigingen nog niet toegepast':''):'Referentie · MIDI onafhankelijk';
 drawVocalNotes();
}
function finishSession(clip,message){const was=playing;stopAudio();current=clip;baseLoop=clone(clip);redrawCurrent();rememberTake();logEntry();renderSession();sessionMessage(message);if(was)playAll();}
function varySession(id){if(!current)return;const targets=current.parts.filter(p=>(!id||p.id===id)&&!sessionConfig.locks[p.id]).map(p=>p.id);if(!targets.length){sessionMessage('Alle gekozen tracks zijn vastgezet.');return;}const seed=newSeed(),clip=clone(current);clip.parts=clip.parts.map(p=>targets.includes(p.id)?rhythmVariation(p,clip.meta.bars,seed,sessionConfig.strength,clip.meta.scale.steps,clip.meta.root):p);relateParts(clip,targets,sessionConfig.relation,sessionConfig.locks);if(typeof performClip==='function'){const performed=performClip(clip,targets);clip.parts=performed.parts;}clip.customEdit=true;clip.meta.seed=seed;$('seed').value=seed;finishSession(clip,(id?PART_DEFS[id].label:targets.length+' tracks')+' · nieuw ritme en nieuwe lengtes. Andere tracks blijven behouden.');}
function afterSessionGeneration(previous){if(!sessionReady)return;sessionMessage('');const locked=sessionConfig.locks;current.parts=current.parts.map(p=>locked[p.id]&&previous?.parts.some(x=>x.id===p.id)?clone(previous.parts.find(x=>x.id===p.id)):p);if(Object.values(locked).some(Boolean))current.customEdit=true;}
function makeVocalSession(fromGenerator=false){
 if(!vocalAnalysis?.segments.length||!vocalBuffer){sessionMessage('Analyseer eerst een vocal.');return;}
 const bpm=Math.round(bound($('vocalBpm').value,40,300,130)),root=+$('vocalRoot').value,sc=$('vocalScale').value,offset=bound($('vocalOffset').value,0,30,0),mode=$('vocalMode').value;
 if(Object.values(sessionConfig.locks).some(Boolean)&&(current?.bpm!==bpm||current?.meta.root!==root||$('scale').value!==sc)){sessionMessage('Ontgrendel tracks voordat je de key of BPM uit de vocal overneemt.');return;}
 let ids=[...document.querySelectorAll('[data-part]:checked')].map(c=>c.dataset.part);if(!ids.some(id=>!['drums','kick'].includes(id)))ids=[...ids,'bass','chords','melody'];
 const generated=guidedVocalParts(vocalAnalysis.segments,ids,root,SCALES[sc].steps,bpm,offset,vocalBuffer.duration,mode,$('seed').value);
 if(generated.bars>128){$('vocalStatus').textContent='Te lang bij dit tempo: maximaal 128 maten.';return;}
 const previous=current;const clip=generateSection({seed:$('seed').value,root,scale:sc,octave:5,bars:generated.bars,bpm,progression:'pedal',parts:ids.filter(id=>['drums','kick'].includes(id)),partOpts:{},tries:8});
 generated.parts.forEach(p=>clip.parts.push({...p,label:PART_DEFS[p.id].label,colour:PART_DEFS[p.id].colour}));clip.bpm=bpm;clip.vocalTiming=true;clip.vocalSourceSerial=vocalSourceSerial;clip.vocalRevision=vocalRevision;clip.vocalOffset=offset;clip.vocalMode=mode;clip.vocalHarmony=generated.harmony.map(h=>({bar:h.bar,degree:h.degree}));
 clip.parts=clip.parts.map(p=>sessionConfig.locks[p.id]&&previous?.parts.find(x=>x.id===p.id)&&previous.meta.bars===clip.meta.bars?clone(previous.parts.find(x=>x.id===p.id)):p);
 if(Object.values(sessionConfig.locks).some(Boolean)&&previous?.meta.bars!==clip.meta.bars){sessionMessage('Ontgrendel tracks om de lengte aan de vocal aan te passen.');return;}
 activeGenre='free';$('bpm').value=bpm;$('root').value=root;$('scale').value=sc;$('structure').value='';document.querySelectorAll('[data-part]').forEach(c=>{c.checked=ids.includes(c.dataset.part);c.closest('.part').classList.toggle('active',c.checked);});
 vocalLinked=true;$('loop').checked=false;finishSession(clip,'MIDI gemaakt uit '+vocalAnalysis.segments.length+' zangnoten. '+generated.harmony.length+' maten harmonie op basis van de zang.');$('vocalStatus').textContent=mode==='answer'&&!generated.parts.some(p=>!['bass','chords','pad','harmony'].includes(p.id)&&p.events.length)?'Geen bruikbare zangpauzes voor een antwoordmelodie. Kies Volgen of een andere frase.':'Begeleiding klaar. Vocal en MIDI spelen samen via de bovenste Play-knop.';selectView('generator');drawer.open=false;document.querySelector('.rollbox').scrollIntoView({block:'center'});
}
sessionReady=true;selectInstrument('bass');renderVocalEditor();

// Section variations reuse the same source harmony; each section has its own rhythmic seed.
const plainArrange=arrangeClip;
arrangeClip=function(source,sections){
 const clip=plainArrange(source,sections);let bar=0;
 sections.forEach((s,i)=>{const start=bar*1920,end=(bar+s.bars)*1920;if(s.variation&&s.variation!=='same')clip.parts.forEach(p=>{if(sessionConfig.locks[p.id])return;const selected=p.events.filter(e=>e.tick>=start&&e.tick<end).map(e=>({...e,tick:e.tick-start}));const variant=rhythmVariation({...p,events:selected},s.bars,source.meta.seed+':section:'+i,s.variation,clip.meta.scale.steps,clip.meta.root);p.events=[...p.events.filter(e=>e.tick<start||e.tick>=end),...variant.events.map(e=>({...e,tick:e.tick+start}))].sort((a,b)=>a.tick-b.tick||a.midi-b.midi);});bar+=s.bars;});clip.vocalTiming=false;delete clip.vocalSourceSerial;return clip;
};
const renderArrangementBase=renderArrangement;
renderArrangement=function(){renderArrangementBase();document.querySelectorAll('.arr-settings').forEach((row,i)=>{const label=document.createElement('label');label.innerHTML='Ritme <select data-section-variation="'+i+'">'+[['same','Bron behouden'],['subtle','Subtiel'],['explore','Nieuwe groove'],['wild','Avontuurlijk']].map(([value,name])=>'<option value="'+value+'" '+((arrSections[i].variation||'same')===value?'selected':'')+'>'+name+'</option>').join('')+'</select>';row.appendChild(label);});};
$('arrRows').addEventListener('change',e=>{if(e.target.dataset.sectionVariation===undefined)return;arrSections[+e.target.dataset.sectionVariation].variation=e.target.value;saveToHash();rememberTake();});
const sectionExport=document.createElement('div');sectionExport.className='section-export';sectionExport.innerHTML='<h3>Losse sectie naar je DAW</h3><p class="hint">Elke export start op maat 1. Gebruik dezelfde trackklank voor intro, build en drop.</p><div class="action-row"><select id="sectionExportTrack" aria-label="Track voor sectie-export"></select><select id="sectionExportIndex" aria-label="Sectie voor export"></select><button id="exportSection">'+icon('download')+' Download sectie-MIDI</button></div>'; $('arrRows').after(sectionExport);
const renderArrFinal=renderArrangement;renderArrangement=function(){renderArrFinal();const value=$('sectionExportTrack').value;const source=baseLoop||current;$('sectionExportTrack').innerHTML=(source?.parts||[]).map(p=>'<option value="'+p.id+'">'+p.label+'</option>').join('');if(source?.parts.some(p=>p.id===value))$('sectionExportTrack').value=value;$('sectionExportIndex').innerHTML=arrSections.map((s,i)=>'<option value="'+i+'">'+escapeHtml(s.name)+'</option>').join('');$('exportSection').disabled=!source;};
$('exportSection').onclick=()=>{try{const clip=arrangeClip(baseLoop||current,arrSections),i=+$('sectionExportIndex').value,s=arrSections[i],id=$('sectionExportTrack').value,start=arrSections.slice(0,i).reduce((n,s)=>n+s.bars,0)*1920,end=start+s.bars*1920,p=clip.parts.find(p=>p.id===id),events=(p?.events||[]).filter(e=>e.tick>=start&&e.tick<end).map(e=>({...e,tick:e.tick-start,dur:Math.min(e.dur,end-e.tick)}));if(!events.length){$('arrStatus').textContent='Deze track speelt niet in de gekozen sectie.';return;}download(buildMidi([{id,name:PART_DEFS[id].label,events}],clip.bpm,s.bars*1920),fileStem()+'_'+id+'_'+s.name.replace(/[^a-z0-9_-]/gi,'_')+'.mid');$('arrStatus').textContent='Sectie geëxporteerd vanaf maat 1.';}catch(e){$('arrStatus').textContent=e.message;}};
$('view-arrange').querySelector(':scope > .hint').textContent='Kies per sectie een eigen groove. Vastgezette tracks behouden hun bronritme. Vocal-audio wordt niet herhaald in het arrangement.';
// Keep the middle of the screen focused on notes, with optional details underneath.
document.querySelector('.rollbox').after($('mixerPanel'));
const readoutDetails=document.createElement('details');readoutDetails.className='session-extra';readoutDetails.innerHTML='<summary>Trackoverzicht & exporthulp</summary>'; $('readout').before(readoutDetails);readoutDetails.appendChild($('readout'));document.querySelectorAll('main > .hint, main > .footer-note').forEach(p=>readoutDetails.appendChild(p));
if(innerWidth<1190)document.body.classList.add('inspector-closed');
const nav=document.querySelector('.topnav');['generator','sound','arrange','ideas','tools','check'].forEach(id=>nav.appendChild($('tab-'+id)));
$('tab-generator').textContent='MIDI';$('tab-sound').textContent='Sound';$('tab-ideas').textContent='Takes';$('tab-tools').textContent='Tools';$('tab-check').textContent='Check';

const audioOptions=document.createElement('details');audioOptions.className='vocal-audio-options';audioOptions.innerHTML='<summary>Audio beheren & solo luisteren</summary>'; $('vocalWave').after(audioOptions);audioOptions.appendChild($('vocalAudio'));const audioButtons=document.createElement('div');audioButtons.className='sound-strip';audioOptions.appendChild(audioButtons);audioButtons.append($('cancelVocal'),$('removeVocal'));
const analyseRow=document.createElement('div');analyseRow.className='sound-strip';$('vocalStatus').after(analyseRow);analyseRow.appendChild($('analyseVocal'));
const linkOptions=document.createElement('details');linkOptions.className='vocal-link-options';linkOptions.innerHTML='<summary>Alleen audio koppelen / verder zonder vocalsturing</summary><p class="hint">Koppelen verandert geen noten. Verder als vrije MIDI stopt het genereren vanuit zang, maar je kunt de audio blijven meeluisteren.</p>'; $('vocalContent').appendChild(linkOptions);linkOptions.append($('linkVocalReference'),$('freeVocalMidi'));
$('vocalMode').parentElement.nextElementSibling.textContent='Zangnoten sturen de melodie. Akkoorden worden per maat gekozen op basis van de aanwezige zangnoten; bas en harmonie delen die keuze. Geen transcriptie van de originele akkoorden.';
$('vocalContent').querySelectorAll('.sound-strip').forEach(row=>{if(!row.children.length)row.remove();});
$('vocalScale').closest('.tool-card').appendChild($('keyCandidates')); // Keep alternate keys nearby but out of the main step order.
$('inspector').addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.add('inspector-closed');document.querySelector('[data-select-track="'+selectedInstrument+'"]')?.focus();}});
