/* 3.0: one editing surface, three focused tools, scalable inline brand. */
const studioMark='<svg class="studio-mark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" aria-hidden="true"><rect width="64" height="64" rx="16" fill="#16282e"/><path d="M14 46V18h7l11 16 11-16h7v28h-8V32L32 46 22 32v14z" fill="#bdf5df"/><path d="M43 10h11v4H43z" fill="#ff967f"/></svg>';
document.querySelector('header h1').innerHTML=studioMark+'<span class="studio-wordmark">MIDI<span>ROOM</span><small>COMPOSITION STUDIO</small></span>';
const favicon=document.createElement('link');favicon.rel='icon';favicon.href='data:image/svg+xml,'+encodeURIComponent(studioMark.replace('class="studio-mark"',''));document.head.appendChild(favicon);
const studioTools=[['sculptor','Frase Sculptor','phraseSculptor','01'],['groove','Groove DNA','grooveDNA','02'],['vocal','Vocal Conversation','vocalConversation','03']];
const editingTray=document.createElement('section');editingTray.id='editingTray';editingTray.innerHTML='<div class="editing-heading"><div><span class="eyebrow">IDEA → EXPRESSION</span><h3>Shape your sound.</h3></div><div role="tablist" aria-label="MIDI-bewerking" class="editing-tabs">'+studioTools.map(([key,label,id,n])=>'<button type="button" id="studioTool-'+key+'" role="tab" aria-controls="'+id+'" aria-selected="false" tabindex="-1"><span>'+n+'</span>'+label+'</button>').join('')+'</div></div><div id="editingPanels"></div>';
const mainRoll=document.querySelector('.rollbox');document.querySelector('.daw-toolbar').after(mainRoll);document.querySelector('#rollViewport').before(editingTray);
for(const [key,label,id] of studioTools){const panel=$(id);if(panel){$('editingPanels').appendChild(panel);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby','studioTool-'+key);panel.tabIndex=0;}}
function selectStudioTool(key){studioTools.forEach(([k,label,id])=>{const on=k===key;$('studioTool-'+k).setAttribute('aria-selected',String(on));$('studioTool-'+k).tabIndex=on?0:-1;if($(id)){$(id).hidden=!on;if(on&&$(id).tagName==='DETAILS')$(id).open=true;}});if(key==='vocal'&&typeof renderConversation==='function')renderConversation();window.dispatchEvent(new Event('resize'));}
studioTools.forEach(([key],i)=>{const tab=$('studioTool-'+key);tab.onclick=()=>selectStudioTool(key);tab.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;selectStudioTool(studioTools[n][0]);$('studioTool-'+studioTools[n][0]).focus();};});
selectStudioTool('sculptor');
const exploration=document.createElement('div');exploration.className='exploration-stack';mainRoll.after(exploration);['vocalDrawer','discoveryLab','sceneRack'].forEach(id=>{if($(id))exploration.appendChild($(id));});
document.querySelector('.workspace-heading h2').innerHTML='Make the next <em>idea.</em>';
const studioKicker=document.createElement('span');studioKicker.className='studio-kicker';studioKicker.textContent='MIDIROOM / CREATIVE WORKSPACE';document.querySelector('.workspace-heading h2').before(studioKicker);
mainRoll.after($('exports'));$('exports').after(exploration);mainRoll.before($('meta'));
